### ISSUE TITLE
Problem in combination with MSI builder

### ISSUE THREAD

**Issue by Palollo** [yck1509/ConfuserEx#143]
If the packer is used, the final exe file (myApp.exe) produces the following error message when it is processed by the Visual Studio MSI Builder:
> Unable to find file 'kui' of multi-file assembly 'myApp.exe'.

**Comment by yck1509** [comment]
I just test it and it seems you could create a empty file named 'koi' next to the obfuscated output to prevent the error.

**Comment by AndresRohr** [comment]
Yes, thumbs up, works perfectly. But the file MUST be of size 0. And it will appear also on the target machine after an installation. Funny.
