### ISSUE TITLE
"inherit" attribute makes no sense

### ISSUE THREAD

**Issue by Palollo** [yck1509/ConfuserEx#153]
Look at this project file:
```xml
<project outputDir="..\PROTECTED" baseDir=".\UNPROTECTED" xmlns="http://confuser.codeplex.com">
  <rule pattern="true" preset="none" inherit="false">
     <protection id="anti debug" />
     <protection id="anti dump" /> 
     <protection id="anti ildasm" />
     <protection id="anti tamper" />
  </rule>

  <module path="main.exe">
  <module path="lib.dll">
  <module path="update.exe">
    <rule pattern="true" preset="none" inherit="true">
      <protection id="anti tamper" action="remove" />
    </rule>
  </module>
</project>
```

I want to remove the "anti tamper" protection only in the last module, and only remove that protection, so I set the attribute *inherit="true"* and then the attribute *action="remove"*. But the attribute *preset="none"* clear the previous protection set (in the global rule).
Actually I don't know in which case *inherit="true"* comes useful.
Maybe the *inherit* attribute should make to ignore the *preset* attribute?

**Comment by yck1509** [comment]
Your project settings should be working as intended. The protection set is only cleared when inherit is set as 'false'. My simple test shows that it is working correctly here. Do you have any sample files that can allow me to reproduce the problem?

**Comment by Palollo** [comment]
I'm very sorry, I can't reproduce the problem again. I think I did some wrong in the previous tests, so probably there is no issue.

By the way, I have to remove the "anti tamper" protection because it cause a false positive (HEUR:Trojan.Win32.Generic) in a Kaspersky analysis. I know it is common in many ofuscators, it's a bummer and hard to fix, but easy to avoid in this case. It can be interesting to include a warning in the documentation.
