### ISSUE TITLE
Rename AnonymousType

### ISSUE THREAD

**Issue by bprg** [yck1509/ConfuserEx#156]
Please improvement ``AnonymousType`` renaming, It seems commercial obfuscator do this job better.
Thanks in advance.

**Comment by yck1509** [comment]
I'm not sure what you mean by improving anonymous type renaming. Do you have any example about it?

**Comment by bprg** [comment]
Ten days ago I was sent to you'r email ``DevExpress.OutlookInspiredApp.Wpf``.  It seems Eaz renamed generic param.

![eaz](https://cloud.githubusercontent.com/assets/706507/5758630/c49e23c6-9c7b-11e4-832b-1564043b9e3d.png)
![confuser](https://cloud.githubusercontent.com/assets/706507/5758632/c6c7cc56-9c7b-11e4-8573-a51fc4026008.png)

**Comment by yck1509** [comment]
Should be fixed in 97b541b4290d78c54bba25f1d64a2515c8fea4aa.

**Comment by bprg** [comment]
Thanks Ki but after rename symbol doesn't run ``DevExpress.OutlookInspiredApp.Wpf`` project can you solve this problem in the future ?

**Comment by yck1509** [comment]
You need to exclude some classes from renaming in order to make it run. e.g. FilterInfo.*, .*View

**Comment by bprg** [comment]
OK, Thanks a lot.
