### ISSUE TITLE
Name protection does not handle interfaces correctly

### ISSUE THREAD

**Issue by OndrejPetrzilka** [yck1509/ConfuserEx#157]
Priject A:

interface IMyInterface
{
  void Method();
}

Project B:

class SomeClass
{
  public void Method();
}

class AnotherClass : SomeClass, IMyInterface
{
}

This is valid in C#, no need to define Method() in AnotherClass.
After obfuscating (rename) Project B, it triggers exception:
System.TypeLoadException: Method '=vQE2c7I6c5GGgBR7IFPFvx9Jd8=' in type '=MyA7qP3egZSNcyzePBicnJg1aW=' from assembly 'ProjectB.....' does not have an implementation.

it seems that C# notices that Method() with required name and signature is already defined, so interface is 'satisfied'. However ConfuserEx does not notice that and does not take it into account during rename.

This is problem, because in VS, everything looks fine, but after obfuscation, it crashes.

**Comment by yck1509** [comment]
Your problem is same as #105, which is already fixed. I just tried the code you provided and it runs without problem. Is there any sample dll/exe that can reproduce the problem?

**Comment by OndrejPetrzilka** [comment]
I'll build from sources and try again, thanks for help and sorry for duplicate!

**Comment by OndrejPetrzilka** [comment]
OK this case is fine, other case is problem, do you want me to make a new ticket or write it here?

**Comment by yck1509** [comment]
I suppose you could open a new issue.

**Comment by OndrejPetrzilka** [comment]
Closing as duplicate to #105 
Already fixed on trunk
