### ISSUE TITLE
Anti-tamper or anti-dump causes VerificationException

### ISSUE THREAD

**Issue by akikari** [yck1509/ConfuserEx#159]
If AllowPartiallyTrustedCallers attribute is defined in a library, the ConfuserEx anti-tamper or anti-dump protection causes VerificationException in the web application:

VerificationException: Operation could destabilize the runtime.

Sample solution:
http://devsys.hu/Downloads/DestabilizeIssue.zip

After unpacking copy ConfuserEx binaries into the solution's ConfuserEx directory.
Start the application and click on the "Call library method" button.

I provided more ConfuserEx projects. See ConfuserExProject directory.

If I don't use anti-tamper and anti-dump or AllowPartiallyTrustedCallers attribute, there is no exception.

**Comment by yck1509** [comment]
The wiki of [Anti Tamper Protection](https://github.com/yck1509/ConfuserEx/wiki/Anti-Tamper-Protection) and [Anti Dump Protection](https://github.com/yck1509/ConfuserEx/wiki/Anti-Dump-Protection) has stated that they would produces unverifiable modules, which is most likely the cause of the exception.

**Comment by akikari** [comment]
Thank you. I will implement another anti-tamper method.
