### ISSUE TITLE
How can I use parameters in ConfuserEx?

### ISSUE THREAD

**Issue by Mauripereg** [yck1509/ConfuserEx#162]
Hello,
I'm using Confuserex and dont understand how to use parameters.

I do an example:

I want to introduce in a rule a protection anti debug and for this i want to set parameter "mode" to "antinet". how can I do it?!

in the GUI its no possible (I have found no way to do it...)

May I edit the project?

My project is :

<project outputDir="D:\Generazione Codici\ExplorHD\Controlla\bin\Release\Confused" baseDir="D:\Generazione Codici\ExplorHD\Controlla\bin\Release" debug="true" xmlns="http://confuser.codeplex.com">
<rule pattern="true" preset="maximum" inherit="false">

<protection id="anti ildasm" />
<protection id="anti tamper" />
<protection id="constants" />
<protection id="ctrl flow" />
<protection id="anti dump" />
<protection id="anti debug" />
<protection id="invalid metadata" />
<protection id="ref proxy" />
<protection id="resources" />

</rule>
<module path="Control.exe" />
<module path="ExplorHD.dll" />
<module path="Keymanage.dll" />
</project>

where can I introduce parameter?

thanks to all!!!!!

**Comment by yck1509** [comment]
Hi,
You can refer to the [Project Format](https://github.com/yck1509/ConfuserEx/blob/master/docs/ProjectFormat.md) documentation for more details on *.crproj format. Specifically, you can apply parameter using the following syntax:
```XML
<protection id="anti debug">
	<argument name="mode" value="antinet" />
</protection>
```

**Comment by Mauripereg** [comment]
Ok
it works!!

Thanks
