### ISSUE TITLE
How to exclude a methode and the atributes for COM visibility from Obfuscation

### ISSUE THREAD

**Issue by ranjicgnr** [yck1509/ConfuserEx#163]
First hats off for a great work.
My question is how to exclude a com visible class and the atributes from obfuscation. Will the Obfuscation atributes work when i am using a crproj to run in Confuser.CLI.exe

I am getiing the below error when i use Confuser.CLI.exe.

C:\>D:\Software\ConfuserEx\Confuser.CLI.exe -o="D:\Development\Visual Studio\Tes
tDll\TestDll\bin\Release\Confused" "D:\Development\Visual Studio\TestDll\TestDll
\bin\Release\TestDll.dll"
 [INFO] ConfuserEx v0.4.0 Copyright (C) Ki 2014
 [INFO] Running on Microsoft Windows NT 6.2.9200.0, .NET Framework v2.0.50727.63
87, 64 bits
[DEBUG] Discovering plugins...
 [INFO] Discovered 10 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
 [INFO] Loading 'D:\Development\Visual Studio\TestDll\TestDll\bin\Release\TestDl
l.dll'...
[ERROR] Unknown error occurred.
Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boo
lean add)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Confuser.CLI.ObfAttrParser.ParseProtectionString(ProtectionSettings settin
gs, String str) in e:\Source\Public\Confuser2\Confuser.CLI\ObfAttrParser.cs:line
 183
   at Confuser.CLI.ObfAttrMarker.ApplySettings(ConfuserContext context, IDnlibDe
f def, IEnumerable`1 infos) in e:\Source\Public\Confuser2\Confuser.CLI\ObfAttrMa
rker.cs:line 166
   at Confuser.CLI.ObfAttrMarker.ProcessModule(ModuleDefMD module, ConfuserConte
xt context, String snKeyPath, String snKeyPass, List`1 settingAttrs, Dictionary`
2 namespaceAttrs) in e:\Source\Public\Confuser2\Confuser.CLI\ObfAttrMarker.cs:li
ne 256
   at Confuser.CLI.ObfAttrMarker.MarkModule(ConfuserProject proj, ConfuserContex
t context, ModuleDefMD module, Boolean isMain, Tuple`2& packerInfo) in e:\Source
\Public\Confuser2\Confuser.CLI\ObfAttrMarker.cs:line 232
   at Confuser.CLI.ObfAttrMarker.MarkProject(ConfuserProject proj, ConfuserConte
xt context) in e:\Source\Public\Confuser2\Confuser.CLI\ObfAttrMarker.cs:line 36
   at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, Ca
ncellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngin
e.cs:line 123
Failed at 5:58 PM, 0:00 elapsed.

Here is the decleratives i used in my test program

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Reflection;

[assembly: Obfuscation(Exclude = false, Feature = "generate debug symbol: false")]
[assembly: Obfuscation(Exclude = false, Feature = "random seed:Test")]
[assembly: Obfuscation(Exclude = false, Feature = "strong name key:D:\\Development\\Visual Studio\\TestDll\\TestDll\\TestDll.pfx")]
[assembly: Obfuscation(Exclude = false, Feature = "strong name key password:Ranji060485")]

//[assembly: Obfuscation(Exclude = false, Feature = "packer:compressor(key=dynamic)")]
[assembly: Obfuscation(Exclude = false, Feature = "preset(none);+ctrl flow;")]

[assembly: Obfuscation(Exclude = false, Feature = "namespace 'TestDll':-rename")]

namespace TestDll
{

    [Obfuscation(Exclude = false, Feature = "default")]
    public class TestClass
    {
        public void TestMethode1()
        {
            int test1 = 2;
            int test2 = 5;

            int Test3 = test1 + test2;
        }
    }

    [Obfuscation(Exclude = true, ApplyToMembers = false)]
    public class TestClass1
    {
        public void TestMethode2()
        {
            int test4 = 2;
            int test5 = 5;

            int Test6 = test4 + test5;
        }
    }
}

**Comment by yck1509** [comment]
Hi,
You used "default" as the Feature of ObfuscationAttribute. ConfuserEx does not support that.

**Comment by Ruffio** [comment]
can this be closed?

**Comment by ranjicgnr** [comment]
Please close the ticket.

Thanks & Regards

Ranjith K R
Ph : +919746562440
