### ISSUE TITLE
Exports table destroyed

### ISSUE THREAD

**Issue by Anthonywolfe** [yck1509/ConfuserEx#172]
After running a single C++/CLI dll through ConfuserEx 4.0 with or without any protections enabled it seems to strip the exports table. Am I doing something wrong or is this intended?

**Comment by yck1509** [comment]
As I just mentioned in #171, not much testing was done with C++/CLI dlls. I'll try to gather some samples of C++/CLI dlls and fix the obfuscation.

**Comment by yck1509** [comment]
Also, if you don't mind, you could send your dlls to confuser.net@gmail.com and I'll try to fix the obfuscation for you.

**Comment by yck1509** [comment]
Fixed privately.
