### ISSUE TITLE
Visual Studio integration .. an error

### ISSUE THREAD

**Issue by mrjohnr** [yck1509/ConfuserEx#173]
Hi,I'm using confuserex,i made some changes to vbproj file to integrate id with confuserex on build
that the code I found
if $(ConfigurationName)==Release (
cd “$(TargetDir)”
“c:\path_to_\confuser Release\confuser.console.exe” “$(SolutionDir)confuserSettings.crproj”
copy /y Confused\*.*
rmdir /s /q Confused
) else (
echo “not in release mode, not obfuscating”
)

and I use:
<PropertyGroup>
    <PostBuildEvent>
    If $(ConfigurationName)==Release (
        cd $(TargetDir)
        c:\Confuser\Confuser.CLI.exe $(ProjectDir)confuserSettings.crproj
     )
   </PostBuildEvent>
  </PropertyGroup>

confuserSettings.crproj is confuser project

the only thing I could not resolved is to use in build mode obfuscated file

i think these commands is doing that:

copy /y Confused\*.*
rmdir /s /q Confused

I don't used them becase I got this error:

http://i.stack.imgur.com/jJaWH.png

**Comment by yck1509** [comment]
Hi,
Did you used anti debug? If so, the protection would crash under debugger (i.e. in Visual Studio).

**Comment by mrjohnr** [comment]
Hi,I'm using default VS settings,no anti debug
thanks

**Comment by yck1509** [comment]
Do you mind posting your project file (i.e. confuserSettings.crproj) for me to have a look?

**Comment by mrjohnr** [comment]
<project outputDir="C:\aaaa\WindowsApplication1\WindowsApplication1\bin\Release\Confused" baseDir="C:\aaaa\WindowsApplication1\WindowsApplication1\bin\Release" xmlns="http://confuser.codeplex.com">
  <rule pattern="true" inherit="false" />
  <packer id="compressor" />
  <module path="WindowsApplication1.exe">
    <rule pattern="true" preset="maximum" inherit="false" />
  </module>
</project>


thanks!

**Comment by yck1509** [comment]
You used maximum preset, which includes anti debug. Try removing that protection.

**Comment by mrjohnr** [comment]
I've removed, but error is present.If I remove the protection what obfuscation is done?
What settings should I do for normal/good obfuscation,confuserEx gives many settings,what I have to chose?
I'm currently trying to upgrade from Eazfuscator latest free version.
thanks for your time and answers!

**Comment by yck1509** [comment]
If you don't mind, you could send the related files to confuser.net@gmail.com and I would help you to solve the problem.

**Comment by mrjohnr** [comment]
I've sent files,thanks!

**Comment by yck1509** [comment]
Fixed.

**Comment by damozaz** [comment]
How did you fix it?
