### ISSUE TITLE
Code Cracker deobfuscator tools for ConfuserEx

### ISSUE THREAD

**Issue by lynx550** [yck1509/ConfuserEx#175]
Hello yck,
Recently I was aware that CodeCracker from Romania (I am sure you know who I am referencing) created some new deob tools for Confuser Ex which makes it easy for Noobs to recover the source of a ConfuserEx protected assembly.

After looking into the source of the codecracker tools I noticed that he was referencing many statically declared names and strings that ConfuserEX uses.  I was wondering if you ever considered creating a way to either have these static names and strings dynamic or randomized so that it would be hard for crackers to create such tools? Or make a settings page in ConfuserEX where we can change these static values without needing to modify and recompile your obfuscator?

**Comment by yck1509** [comment]
Hi,
I'm aware of the tools you're referring to. ConfuserEx already had a great amount of randomizing, however, there are some parts that can't simply be randomized, for example, the structure of decryption routines. I'm working on a solution to defeat these tools. Hopefully it should be ready in March. In the meanwhile, you could try to use some other parameters as described in wiki as not much of them are fully supported by those tools.

**Comment by lynx550** [comment]
With that in mind I tried using these parameters for declarative obfuscation as you suggested however I cannot get it to work for my vb.net project.  I am not sure if the below syntax is correct.

<Assembly: Obfuscation(Exclude:=False, Feature:="constants(mode=dynamic,decodercount=10);ctrl flow(predicate=expression);ref proxy(mode=strong,encoding=expression);resources(mode=dynamic);anti tamper(key=dynamic);")>

**Comment by lynx550** [comment]
You can close this out.....I figured it out.

**Comment by DeathGodAoTTG** [comment]
where could you get these tools

**Comment by Someone-NEW** [comment]
¸No one simple tool out there for NOOBS like me to deobfuscate some plugin too see what the hex have one of the antipiracy system to easy search wich methot they use to be able noob like me crack it to be use at home server for example  :( :( :( i learn learn but i dont know anything more like before.
