### ISSUE TITLE
Resolving dependencies issue with WP8 project

### ISSUE THREAD

**Issue by nickwright-refoint** [yck1509/ConfuserEx#176]
I'm receiving the following error when trying to Resolve a WP8 base project i.e. the project containing the xaml views. Here is the error:

 [INFO] Resolving dependencies...
[ERROR] Failed to resolve dependency of 'RPL.CSCS.GoSmartWP.ViewModels.dll'.
Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime
   at dnlib.DotNet.Extensions.ResolveThrow(IAssemblyResolver self, IAssembly assembly, ModuleDef sourceModule) in c:\projects\confuserex\dnlib\src\DotNet\IAssemblyResolver.cs:line 113
   at Confuser.Core.ConfuserEngine.Inspection(ConfuserContext context) in c:\projects\confuserex\Confuser.Core\ConfuserEngine.cs:line 254
Failed at 17:25, 0:00 elapsed.

I also get this on one of my class libraries as well (the ViewModel project). The other five projects work fine, and on Agressive setting as well. I also have included the WP8 path in the settings (as recommended on the wiki)

I'm using the latest 4.0-52-gc43081b (exe dated 20-Feb-2015).

Thanks.

**Comment by yck1509** [comment]
Hi,
I'm not quite sure about the issue, as I don't have tests about WP8 application. If you don't mind, you could send your files to confuser.net@gmail.com for me to fix the issue.

**Comment by nickwright-refoint** [comment]
Hi, I’ve managed to get this working now. My WP8 app is a Silverlight version, and therefore required the following additional Probe Path (probably useful to put this on your GitHub wiki):

<probePath>C:\Program Files (x86)\Windows Phone Silverlight Kits\8.1\Windows MetaData</probePath>

Thank you for your support.

**Comment by yck1509** [comment]
Thanks for your info! I've added it to the wiki.
