### ISSUE TITLE
About the PDB

### ISSUE THREAD

**Issue by antasis9** [yck1509/ConfuserEx#177]
Hello Developers,

Thank you for your working on ConfuserEx :+1: 

I have a one question about the PDB.
When we build our application without ConfuserEx, we can use pdb files for debugging.
But we build it with ConfuserEx, we can't use pdb files for debugging.

Please let me know how I can use the pdb files with ConfuserEx.

**Comment by yck1509** [comment]
Hi,
You could

**Comment by antasis9** [comment]
I checked 'Generate Debug Symbols' and protect it and meet below error.
Do you know how I can fix it? I used v0.4.0 version

[ERROR] Unknown error occurred.
Exception: System.BadImageFormatException: 프로그램을 잘못된 형식으로 로드하려고 했습니다. (예외가 발생한 HRESULT: 0x8007000B)
   위치: dnlib.DotNet.Pdb.Dss.IMetaDataDispenser.OpenScope(String szScope, UInt32 dwOpenFlags, Guid& riid, Object& ppIUnk)
   위치: dnlib.DotNet.Pdb.Dss.SymbolReaderCreator.Create(String assemblyFileName) 파일 e:\Source\Public\Confuser2\dnlib\src\DotNet\Pdb\Dss\SymbolReaderCreator.cs:줄 63
   위치: dnlib.DotNet.ModuleDefMD.LoadPdb() 파일 e:\Source\Public\Confuser2\dnlib\src\DotNet\ModuleDefMD.cs:줄 517
   위치: Confuser.Core.Marker.MarkProject(ConfuserProject proj, ConfuserContext context) 파일 e:\Source\Public\Confuser2\Confuser.Core\Marker.cs:줄 122
   위치: Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) 파일 e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:줄 122
Failed at 오전 8:57, 0:00 elapsed.

**Comment by yck1509** [comment]
Hi,
You might want to try the latest builds at the [CI Server](https://ci.appveyor.com/project/yck1509/confuserex).

**Comment by antasis9** [comment]
I try to use latest version (0.4.0-59).
But I met another error.

 [INFO] ConfuserEx v0.4.0-59-g209f52f Copyright (C) Ki 2014
 [INFO] Running on Microsoft Windows NT 6.1.7601 Service Pack 1, .NET Framework v4.0.30319.18444, 32 bits
[DEBUG] Discovering plugins...
 [INFO] Discovered 10 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
 [INFO] Loading 'AAA.exe'...
 [INFO] Initializing...
[DEBUG] Building pipeline...
 [INFO] Resolving dependencies...
[DEBUG] Checking Strong Name...
[DEBUG] Creating global .cctors...
[DEBUG] Watermarking...
[DEBUG] Executing 'Name analysis' phase...
[DEBUG] Building VTables & identifier list...
[DEBUG] Analyzing...
[DEBUG] WPF found, enabling compatibility.
[ERROR] Unknown error occurred.
Exception: Confuser.Core.UnreachableException: Unreachable code reached.
   위치: Confuser.Renamer.Analyzers.LdtokenEnumAnalyzer.Analyze(ConfuserContext context, INameService service, IDnlibDef def) 파일 c:\projects\confuserex\Confuser.Renamer\Analyzers\LdtokenEnumAnalyzer.cs:줄 48
   위치: Confuser.Renamer.AnalyzePhase.Analyze(NameService service, ConfuserContext context, ProtectionParameters parameters, IDnlibDef def, Boolean runAnalyzer) 파일 c:\projects\confuserex\Confuser.Renamer\AnalyzePhase.cs:줄 104
   위치: Confuser.Renamer.AnalyzePhase.Execute(ConfuserContext context, ProtectionParameters parameters) 파일 c:\projects\confuserex\Confuser.Renamer\AnalyzePhase.cs:줄 55
   위치: Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context) 파일 c:\projects\confuserex\Confuser.Core\ProtectionPipeline.cs:줄 138
   위치: Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context) 파일 c:\projects\confuserex\Confuser.Core\ConfuserEngine.cs:줄 206
   위치: Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) 파일 c:\projects\confuserex\Confuser.Core\ConfuserEngine.cs:줄 160

**Comment by antasis9** [comment]
The latest version is working :) thank you for your help.
