### ISSUE TITLE
[ERROR] Failed to resolve dependency

### ISSUE THREAD

**Issue by knaveeng** [yck1509/ConfuserEx#179]
1) ConfuserEx is throwing error "Failed to resolve dependency".  The dll is present in the folder.
2) If I specify the problematic dll in the project,  it includes additional warning
    [WARN] [log4net.dll] SN Key is not provided for a signed module, the output may not be working. 

The log of case 1 is included below.

Help is greatly appreciated !!!

[INFO] ConfuserEx v0.4.0 Copyright (C) Ki 2014
 [INFO] Running on Microsoft Windows NT 6.1.7601 Service Pack 1, .NET Framework v4.0.30319.1022, 64 bits
[DEBUG] Discovering plugins...
 [INFO] Discovered 10 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
 [INFO] Loading 'Coal_Allocation_Main.exe'...
 [INFO] Initializing...
[DEBUG] Building pipeline...
 [INFO] Resolving dependencies...
[DEBUG] Checking Strong Name...
[DEBUG] Creating global .cctors...
[DEBUG] Watermarking...
[DEBUG] Executing 'Name analysis' phase...
[DEBUG] Building VTables & identifier list...
[DEBUG] Analyzing...
 [INFO] Processing module 'Coal_Allocation_Main.exe'...
[DEBUG] Executing 'Invalid metadata addition' phase...
[DEBUG] Executing 'Renaming' phase...
[DEBUG] Renaming...
[DEBUG] Executing 'Anti-debug injection' phase...
[DEBUG] Executing 'Anti-dump injection' phase...
[DEBUG] Executing 'Anti-ILDasm marking' phase...
[DEBUG] Executing 'Encoding reference proxies' phase...
[DEBUG] Executing 'Constant encryption helpers injection' phase...
[DEBUG] Executing 'Resource encryption helpers injection' phase...
[DEBUG] Executing 'Constants encoding' phase...
[DEBUG] Executing 'Anti-tamper helpers injection' phase...
[DEBUG] Executing 'Control flow mangling' phase...
[DEBUG] Executing 'Post-renaming' phase...
[DEBUG] Executing 'Anti-tamper metadata preparation' phase...
[DEBUG] Executing 'Packer info extraction' phase...
 [INFO] Writing module 'koi'...
[DEBUG] Encrypting resources...
 [INFO] Finalizing...
 [INFO] Packing...
[DEBUG] Encrypting modules...
 [INFO] Protecting packer stub...
[DEBUG] Discovering plugins...
 [INFO] Discovered 11 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
 [INFO] Loading 'Coal_Allocation_Main.exe'...
 [INFO] Initializing...
[DEBUG] Building pipeline...
[DEBUG] Executing 'Module injection' phase...
 [INFO] Resolving dependencies...
[ERROR] Failed to resolve dependency of 'Coal_Allocation_Main.exe'.
Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: log4net, Version=1.2.10.0, Culture=neutral, PublicKeyToken=1b44e1d426115821
   at dnlib.DotNet.Extensions.ResolveThrow(IAssemblyResolver self, IAssembly assembly, ModuleDef sourceModule) in e:\Source\Public\Confuser2\dnlib\src\DotNet\IAssemblyResolver.cs:line 134
   at Confuser.Core.ConfuserEngine.Inspection(ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 252
[ERROR] Failed to protect packer stub.
Failed at 9:28 AM, 0:02 elapsed.

**Comment by yck1509** [comment]
Please try the latest builds at the [CI Server](https://ci.appveyor.com/project/yck1509/confuserex).

**Comment by knaveeng** [comment]
Thank You !  
Besides using the new build, I had you eliminate "anti dump" and "rename" feature to make sure the final executable works without error
