### ISSUE TITLE
GUI support for relative base path

### ISSUE THREAD

**Issue by aKzenT** [yck1509/ConfuserEx#181]
Currently it is possible to specify a relative path as the base path, which is very practical when using ConfuserEx in a build server environment with changing paths. The relative path is taken as relative from the ConfuserEx project file which is great.

However it seems that the user interface uses a different logic to resolve relative paths. They are resolved relative to the ConfuserEx installation folder instead.

This is unfortunate as it does not allow project files to be edited while using relative paths.

My suggestion would be to always resolve relative base paths as relative to the project file.

Thanks for this great project!

**Comment by yck1509** [comment]
It was fixed in 347b2328e6c62cee5f6655275bdcee51b2b5d465. You may want to try the latest builds at the [CI Server](https://ci.appveyor.com/project/yck1509/confuserex).

**Comment by aKzenT** [comment]
Oh, that is great news! Thanks for the information and the link to the CI Server! I will try it out tomorrow.
