### ISSUE TITLE
Name protection and exe file: Renaming of all public classes by design?

### ISSUE THREAD

**Issue by barnacleboy** [yck1509/ConfuserEx#184]
When applying the name protection on an exe file also public class names get renamed. Is this by design?

**Comment by barnacleboy** [comment]
When applying the name protection on an exe file also public class names get renames. Is this by design?

**Comment by yck1509** [comment]
Yes, it is by design.

**Comment by barnacleboy** [comment]
Ok, makes sense for me. Thought of a bug first... ;)
