### ISSUE TITLE
Confused .exe uses default app.config

### ISSUE THREAD

**Issue by mrjohnr** [yck1509/ConfuserEx#185]
Hi!
I've  migrate from Eazfuscator to confuserEx but I have a problem: when I upgrade my application to new confused .exe,it  uses default app.config ignoring the existing one,and all settings inside(database path,server ip,etc),there are couple implementations and that is a problem to lost settings,I revert to Eazfuscator  and problem is gone,is there any solution to use confuser and have all settings back?
thanks!

**Comment by yck1509** [comment]
Hi,
There are two possible reason to this problem.
1. Eazfuscator renames the settings class. If this is the case, then there is really no way to do a seamless migration to ConfuserEx --- you'll have to convert the old settings file to the new file.
2. Eazfuscator did not rename the settings class. If this is the case, then the latest build should fix it, as I added special handling to exclude settings class from being renamed.

**Comment by mrjohnr** [comment]
Hi,thanks for your answer
I've made some tests:
with default exe build (no obfusation done) I moved database from default path and also changed the setting for the path, with Eazfuscator : no error (used changed file) but with Confuser I got error,database not found in default location,so there is the problem
Where I can find latest build? thanks!

**Comment by yck1509** [comment]
You can find the latest builds at the [CI Server](https://ci.appveyor.com/project/yck1509/confuserex)

**Comment by mrjohnr** [comment]
Using latest build problem is just the same,thanks

**Comment by mrjohnr** [comment]
There are differences between user.config files,there you can find them both: https://www.dropbox.com/s/rdrtqipkl7clcnl/files.ZIP?dl=0

**Comment by yck1509** [comment]
I cannot reproduce the issue here. Do you mind sharing your *.crproj file?

**Comment by mrjohnr** [comment]
there is  https://www.dropbox.com/s/pvp23yvu2r6undy/conf.zip?dl=0

thanks!

**Comment by yck1509** [comment]
Sadly I still cannot recreate the problem here. Did you try clearing the obfuscated output and settings and redo the whole obfuscation process?

**Comment by mrjohnr** [comment]
You're right there was a problem on my side,seems to work now
Thanks a lot!
