### ISSUE TITLE
Compiling fail

### ISSUE THREAD

**Issue by mat0thew** [yck1509/ConfuserEx#187]
http://i.imgur.com/kPMLkNi.png

Need help! :(

**Comment by MurariAlex** [comment]
Hi,
Don't know if it is the right thing to do (I do it, btw), but just rename the file ConfuserEx_default.snk to ConfuserEx.snk and it works.

**Comment by mat0thew** [comment]
#closed @MurariAlex thx

**Comment by blacker966** [comment]
Where can I find ConfuserEx_default? cause I only see confuser.sln

**Comment by rowboater** [comment]
It's in the root folder I can see it.

**Comment by JellySnake13** [comment]
http://oi60.tinypic.com/315hdhc.jpg

You mean this?

**Comment by rowboater** [comment]
I know what you mean. When I first got the repo i couldn't work out where files were. In the end I downloaded the source and got the files that were missing from there. If you unzip the source from the releases folder then you'll see the snk in the root of that.

**Comment by JellySnake13** [comment]
Thanks @rowboater

**Comment by yck1509** [comment]
Hi,
You're advised to generate your own strong name key in place of the default one. If you don't want to do so, you could run the build script at Build/Build.cmd and it would automatically uses the default one for you.
Also @JellySnake13 is using the old Confuser source code, which is no longer in support. I suggest you to use ConfuserEx instead.
