### ISSUE TITLE
Rename protection with P/Invoke

### ISSUE THREAD

**Issue by hgiritzer** [yck1509/ConfuserEx#193]
Hi,

I noticed that the rename protection also renames imported DLL methods (P/Invoke).
I.e. such a source fragment with the external method "open" is renamed, so the P/Invoke call fails: 
[DllImport("libc.so.6", EntryPoint = "open")]
private static extern int open(string fileName, int mode);

Probably such DllImports should be always ignored when applying rename protection?

Might be related to issue #147.

Regards,
Helmut

**Comment by mrkcur** [comment]
I agree, good point Helmut.

**Comment by yck1509** [comment]
Hi,
As far as I know, if EntryPoint property is specified, the runtime would only search the P/Invoke function by the name in EntryPoint property and ignore the method name. Therefore, it should be safe to rename P/Invoke methods.

**Comment by hgiritzer** [comment]
It seems to me that the EntryPoint property is not used/recognized/evaluated within Mono (Linux).
So, I have to prevent those DLL methods from being obfuscated to make it work.
