### ISSUE TITLE
pattern for items in classes that inherited from a specified class

### ISSUE THREAD

**Issue by witchu** [yck1509/ConfuserEx#194]
for example, prevents all private members in classes that inherited from an interface to be renamed. all private members will be serialize/deserialize.

**Comment by yck1509** [comment]
I've just updated `inherits` pattern to check interface implementation too. Please try the lastest builds at the [CI Server](ci.appveyor.com/project/yck1509/confuserex).

**Comment by witchu** [comment]
Thank you for your updating. But It don't solve my problem. I mean the members of the classes that inherit from the specified interface/class. For example, I want to preserve name of members (s1, i1, ...) in C1, C2, ... (all that inherits from Base)

public class Base
{
}

public class C1 : Base
{
	public String s1;
        private int i1;
}

public class C2 : Base
{
	public String s2;
        private int i2;
}

I use these rules

    <rule pattern=“true" inherit="false”>

      <protection id=“rename"/>

    </rule>

    <rule pattern="inherits(‘Base')" inherit="false">

      <protection id="rename" action="remove" />

    </rule>

And it doesn't work. What is the corrected rules?
