### ISSUE TITLE
How can change renaming mode

### ISSUE THREAD

**Issue by LiangChow** [yck1509/ConfuserEx#197]
How can change renaming mode the GUI ?

**Comment by xmatthias** [comment]
taken from my answer for issue #196:

try to open the project file (*.crproj) and modify the rule for your file as follows (attaching the argument mode...):

```
<rule pattern="true" inherit="false">
      <protection id="rename" >
		<argument name="mode" value="debug" />
	  </protection>
    </rule>
```

this definitely worked for me...

**Comment by LiangChow** [comment]
I want changing settings with GUI version.

**Comment by ElenaMilito** [comment]
@LiangChow , ConfuserEx GUI version is not supported for changing settings, Currently I am using the Ezriz .NET Reactor easy changing all settings from PropertyGrid .

**Comment by xmatthias** [comment]
the changes made in the file itself will still be applicable in the gui-version - just changing them itself is not working atm...

**Comment by yck1509** [comment]
Hi,
Changing modes requires modifying protection parameter, which is not planned to implement. If you would like to modify protection parameter, you could edit the crproj file manually and GUI would still load it fine.

**Comment by mallapurbharat** [comment]
was struggling with the same thing... Thanks xmatthias! :)
