### ISSUE TITLE
XAML Renaming

### ISSUE THREAD

**Issue by ElenaMilito** [yck1509/ConfuserEx#199]
Hi, I've disable XAML renaming ``<argument name="renXaml" value="false" />`` but it still renamed XAML source.
![s1](https://cloud.githubusercontent.com/assets/9071462/6768567/185dc90e-d029-11e4-926f-acb6c9329b61.png)

**Comment by yck1509** [comment]
Hi,
renXaml does not do what you want; it prevents the renaming of XAML file name. If you would like to stop renaming of types used in XAML, you can exclude those types manually.
