### ISSUE TITLE
forceRen/renPublic not work the libraries assembly

### ISSUE THREAD

**Issue by bprg** [yck1509/ConfuserEx#205]
Hi Ki,
I trying forceRen / renPublic Parameters not work with libraries assembly.

**Comment by yck1509** [comment]
Hi,
I don't understand what's your problem. Do you mind including more specific details?

**Comment by bprg** [comment]
Hi, For example try ``ILSpy.exe`` with ``forceRen`` parameter without problem rename all symbols, The later try ``ICSharpCode.NRefactory.CSharp.dll`` with ``forceRen`` parameter Confuser can not be renamed all symbol.

**Comment by bprg** [comment]
Hi Ki,
Can you please tell me are you able to reproduce this issue?

**Comment by bprg** [comment]
Another sample, https://www.dropbox.com/s/tj50v2d5oordce0/Force%20Rename%20Issue.rar?dl=0

**Comment by yck1509** [comment]
You need to use renPublic instead of forceRen to rename all symbols.

**Comment by bprg** [comment]
Thanks The problem was solved.
