### ISSUE TITLE
After upgrade to  v0.5.0 application works strange and got errors

### ISSUE THREAD

**Issue by mrjohnr** [yck1509/ConfuserEx#215]
Hi
After upgrade from  v0.4.0-61-g31e6deb to v0.5.0 application works strange and got errors,our clients confirmed that,they could not use it
I've done some tests,that is one of the errors :  http://i.imgur.com/in5Am3v.png

also,I'm sure I've seen the messagebox shown on the next code with a correct value put on the textbox,that code is there  for couple year and worked

 If Val(txtSum.Text) = 0 Then
          MessageBox.Show("Sum must be >0 !")
            txtSum.Focus()
            Exit Sub
        End If
I've tried again and could not reporoduced

I go back to  v0.4.0-61-g31e6deb all works fine,no errors,so there is something wrong with version  v0.5.0

this is the crproj file:

<project outputDir="D:\mypp\bin\Release\Confused" baseDir="D:\mypp\bin\Release" xmlns="http://confuser.codeplex.com">
  <rule pattern="true" preset="aggressive" inherit="false">
    <protection id="anti debug" action="remove" />
  </rule>
  <module path="D:\mypp\bin\Release\app.exe">
    <rule pattern="true" preset="aggressive" inherit="false">
      <protection id="anti debug" action="remove" />
    </rule>
  </module>
</project>

thanks!

**Comment by mrjohnr** [comment]
Hi !
Tested new ConfuserEx v0.5.0-8-ga1ff399   but I can't create confused exe,from VS I got BUILD FAIL and from confuser GUI(ConfuserEx.exe) errors,switching back to ConfuserEx v0.4.0-61-g31e6deb  VS bulid and ConfuserEx.exe works fine
I've attached 2  pictures

**Comment by yck1509** [comment]
Have you tried the latest build at [the CI server](https://ci.appveyor.com/project/yck1509/confuserex)?

**Comment by mrjohnr** [comment]
tested now with ConfuserEx v0.5.0-10-g6ebeec5 and seems to work,thanks!
