### ISSUE TITLE
[Question] Is Constant Encoding all right ? 

### ISSUE THREAD

**Issue by XenocodeRCE** [yck1509/ConfuserEx#222]
Hey hoe ! 

Doing some test since a few days (especially since  0.5 ;) )

I guess that Constant Encoding doesn't work, or does it ? 

I've built a useless file with 2 Int and an addition, I obfuscated the file and Integers are
still untouched  : 

https://www.virustotal.com/fr/file/d686ef72e255202f331ccc45202b305c91b3cc1c6c4cc572253320bc054e7a56/analysis/1429326176/

https://www.sendspace.com/file/6jhwcq

-----------------------------------------------------------

﻿.method private hidebysig 
	instance void Form1_Load (
		object sender,
		class [mscorlib]System.EventArgs e
	) cil managed 
{
	// Method Token is 0x06000002
	// Method begins at RVA 0x0000206C
	// Code size 15 (0xf)
	.maxstack 2
	.locals init (
		[0] int32 arg_69_1,
		[1] int32 arg_3B_0,
		[2] int32 test
	)

	IL_0000: nop
	IL_0001: ldc.i4 49997
	IL_0006: stloc.0
	IL_0007: ldc.i4.s 16
	IL_0009: stloc.1
	IL_000a: ldloc.0  // arg_69_1
	IL_000b: ldloc.1  // arg_3B_0
	IL_000c: add
	IL_000d: stloc.2
	IL_000e: ret
} // end of method Form1::Form1_Load

-----------------------------------------------------------

   int num = 49997;
   int num2 = 16;
   int num3 = num + num2;

-----------------------------------------------------------

My bad If I'm wrong

**Comment by yck1509** [comment]
Hi,
You need to enable it manually using the `elements` parameter.

**Comment by XenocodeRCE** [comment]
If you BP here : https://github.com/yck1509/ConfuserEx/blob/master/Confuser.Protections/Constants/EncodePhase.cs#L50 Integers are not even detected. 
Also here Numbers are supposed to be handled ; https://github.com/yck1509/ConfuserEx/blob/master/Confuser.Protections/Constants/EncodePhase.cs#L237
