### ISSUE TITLE
ConfuserEx should be released under GPL if it does use any code from Confuser

### ISSUE THREAD

**Issue by lextm** [yck1509/ConfuserEx#225]
First I would like to thank you for creating this project. 

But note that Confuser project was released under GPL, http://confuser.codeplex.com/license So any derived products (if ConfuserEx is) must also be released under GPL unless you get permissions from all copyright holders of the original project.

I raise this concern because currently ConfuserEx is announced to be under MIT which makes famous projects such as IL Repack plans to use some classes. That's generally harmful as then those projects also need to be released under GPL.

Please make sure you either correct the license issue by switching from MIT to GPL, or you get those copyright holders responded.

**Comment by yck1509** [comment]
Hi,
Thanks for raising this question; that's a legitimate concern about the license. However, there is no need to worry about it.

As I mentioned in the project page, ConfuserEx is the successor of Confuser, but in a spiritual way. Although it contains many features from Confuser, most parts were rewritten from scratch, especially the UI, setting format and processing pipeline.

Moreover, I was the main contributor to the original Confuser project (by 'main', only one changeset in the history was not authored by me), so I'm able to re-license my code in MIT license. In additional, all of the other contributions to the original project is irrelevant or not used in ConfuserEx (See below for more details). Therefore, there is no worry of the original GPL code of Confuser 'contaminating' the new MIT code in ConfuserEx.

---

Details about contribution of Confuser project other than mine:
Changeset by christallire on May 12, 2012: Not used in ConfuserEx, compressor is rewritten.
Patch by mistoll on Apr 24, 2013: Not used in ConfuserEx, settings marking is rewritten.
Patch by calumchisholm on Aug 3, 2012: Irrelevant, ConfuserEx project format supports the feature in other ways.
Patch by element109 on Oct 5, 2010: Irrelevant, ConfuserEx uses dnlib, not Mono.Cecil anymore.

---

By the way, I was the sole author of the WPF BAML read/writer you mentioned at the issue referenced, so there is no concern of licensing.

**Comment by lextm** [comment]
Thanks for the clarification. Then there is no more concern. Nice project :)
