### ISSUE TITLE
remove signature

### ISSUE THREAD

**Issue by seagate1992** [yck1509/ConfuserEx#229]
Hi, I'm working on a project, and when I open my setup.exe with notepad++, i can see in clear "Confuserex v0.5.0-custom", is there any way to remove this signature ? :)

**Comment by XenocodeRCE** [comment]
1. Remove the Build folder : /Build
2. Edit GlobalAssemblyInfo.cs in the root of your project.
3. Edit Confuser.Core.CsProj file : remove everything I highlight here -> http://i.imgur.com/bSRWxPQ.png

 If you want to completely remove the watermark, just set AssemblyInformationalVersion value to "" (double quote) in GlobalAssemblyInfo.

**Comment by seagate1992** [comment]
Ok thanks :)

**Comment by yck1509** [comment]
Hello,
That attribute is added at ConfuserEngine.Inspection. You could remove the watermark by removing the relevant parts, however I don't see the need of doing so.
