### ISSUE TITLE
Failed to resolve assembly (MvvmLight)

### ISSUE THREAD

**Issue by Awesomeness2014** [yck1509/ConfuserEx#233]
I'm using MvvmLight (5.0.2) in my WPF application and have therefore embedded the GalaSoft.MvvmLight.dll  as an embedded resource, so that there's only one needed file.

When I try to apply the protection with ConfuserEx v0.5.0 I get the following error:
> [ERROR] Failed to resolve dependency of 'MyApp.exe'.
Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly:  GalaSoft.MvvmLight, Version=5.0.2.32240, Culture=neutral, PublicKeyToken=e7570ab207bcb616
   bei dnlib.DotNet.Extensions.ResolveThrow(IAssemblyResolver self, IAssembly assembly, ModuleDef sourceModule) in E:\Source\Public\Confuser2\dnlib\src\DotNet\IAssemblyResolver.cs:Zeile 113.
   bei Confuser.Core.ConfuserEngine.Inspection(ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:Zeile 254.
Failed at 22:40, 0:00 elapsed.`

I wouldn't even care if this dll could not be protected, but due to that error the whole application fails.

**Comment by yck1509** [comment]
Hi,
You could just put that dll near your application without including it in the protections.

**Comment by Awesomeness2014** [comment]
Yes that would be possible, but I'd like to keep my 1-file solution, due to it's simplicity (easy to deliver, easy to move on disk etc.)
Is there a way to support this use case?

**Comment by yck1509** [comment]
ConfuserEx only need that dll to analyze your application; if you had embedded the dll into your exe, you don't need to keep the dll when you release the application.

**Comment by Awesomeness2014** [comment]
This seems to work, thank you!
