### ISSUE TITLE
Merged and Confused Assembly doesn't work in Mono / Linux

### ISSUE THREAD

**Issue by SirusDoma** [yck1509/ConfuserEx#243]
Hello there!
I was merged my assemblies dependencies and obfuscate it with ConfuserEx 0.5.0 and it's work fine in Windows (Microsoft .NET Framework 2.0)

however, when i port my game to Linux Ubuntu 14.0.4 LTS, the game isn't running, i forgot to copy the exception messages but it say something like reference not found,

while merged assemblies still running in windows and linux (fyi it uses dllmap (.config file)), i have no idea how to make confused assembly running properly.

any ideas?

UPDATE
here the exception message (Main Assembly called OTwo.exe)

`Unhandled Exception:
System.TypeLoadException: Could not load type '‫‫​‍⁮‎‪⁪‭⁮' from assembly 'OTwo, Version=0.0.0.0, Culture=neutral, PublicKeyToken=79bed3e46f0de0fe'.
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type '‫‫​‍⁮‎‪⁪‭⁮' from assembly 'OTwo, Version=0.0.0.0, Culture=neutral, PublicKeyToken=79bed3e46f0de0fe'.`

**Comment by SirusDoma** [comment]
Here the exception message (Main Assembly called OTwo.exe)

`Unhandled Exception:
System.TypeLoadException: Could not load type '‫‫​‍⁮‎‪⁪‭⁮' from assembly 'OTwo, Version=0.0.0.0, Culture=neutral, PublicKeyToken=79bed3e46f0de0fe'.
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type '‫‫​‍⁮‎‪⁪‭⁮' from assembly 'OTwo, Version=0.0.0.0, Culture=neutral, PublicKeyToken=79bed3e46f0de0fe'.`

**Comment by DraTeots** [comment]
It is #212 and  #204
Concise resolution: Fixed, copy on CI server works.

**Comment by SirusDoma** [comment]
Thanks for the reply!
But can you tell me how do i get a copy on CI Server?

I don't really understand, i am new here

**Comment by DraTeots** [comment]
You could find the link on the confuser EX web site.

But here it is 
https://ci.appveyor.com/project/yck1509/confuserex/build/artifacts
