### ISSUE TITLE
Name obfuscation not renaming internal sealed class

### ISSUE THREAD

**Issue by wzoet** [yck1509/ConfuserEx#248]
Hi,
I am working on a project that is using several namespaces. 
All non-public namespaces are removed from the confused source except for one.
This is because it contains an un-confused class. The remaining one is an internal sealed class.
I see no reason why this class should not be renamed.

At second glance, it seems the class is only partially renamed. Some methods have been renamed unreadable, other methods, as well as private as public aren't renamed. 
My guess is that confuserex has a problem with my code somehow.

I can't add any files here, but I could email the source of the unrenamed class.

Thanks in advance!

**Comment by yck1509** [comment]
Hi,
I suppose there are some reflection references to the class. For example, typeof, ResourceManager, etc. If you want me to look for the problems, you could send it to confuser.net@gmail.com
