### ISSUE TITLE
Best Settings for the protection + performance

### ISSUE THREAD

**Issue by xanalab** [yck1509/ConfuserEx#256]
Hello sir,
Can you tell me what is the best settings to get the best protection, but also the performance. Thanks :)

**Comment by XenocodeRCE** [comment]
ConfuserEX is pretty stable enough so you can use maximum settings + packer

**Comment by yck1509** [comment]
Hi,
I can't say the best settings as different application has different need; One settings might work well for one application, but worse for others. In general, the performance of ConfuserEx's should be good enough for general application in default settings.

**Comment by xanalab** [comment]
Thanks for the information. Hope i'll find the best setting for my .net app :)

**Comment by tyronx** [comment]
> ConfuserEX is pretty stable enough so you can use maximum settings + packer

Just for info: Maximum settings broke compatibility with running my application with the Mono Framework.
