### ISSUE TITLE
How to make a custom version of ConfuserEx?

### ISSUE THREAD

**Issue by andrewfamn** [yck1509/ConfuserEx#26]
This is more like a Q&A than an issue report but I don't know where to ask so I post it here. Therefore, I'm sorry about that.
In your FAQ, you mention "a generic deobfuscator for different custom version of ConfuserEx would be virtually impossible to be created."
1. What classes in the source code should I work on in order to make a custom version?
2. Is it helpful if I provide a seed to crproj file?
3. If my application includes a strong name key, does it make harder being deobfuscated?
4. And how do I implement a plug-in?
Thank you very much.

**Comment by damms005** [comment]
Please @yck1509 , I need help with these:

1. Which constants in [this file] (https://github.com/yck1509/ConfuserEx/blob/master/Confuser.Runtime/Constant.cs#L12) can I  change safely without breaking things?

2. Can you recommend a resource where I can learn the basics needed for me to know how to safely customize [this same file] (https://github.com/yck1509/ConfuserEx/blob/master/Confuser.Runtime/Constant.cs#L12) further in order to improve the security of my obfuscated executable. For example, how can I know if it is safe to change the decimals (12, 25, and 27) in the code snippet below (still the same `Constant.cs` file):
```
var n = (uint)Mutation.KeyI1;
for (int i = 0; i < 0x10; i++) 
{
    n ^= n >> 12;
    n ^= n << 25;
    n ^= n >> 27;
    k[i] = n;
}
```

**Comment by Drizin** [comment]
As far as I remember Symmetric-Key cryptography, you are right that you should choose numbers carefully. That is confirmed by Wikipedia on [xorshift](https://en.wikipedia.org/wiki/Xorshift), that explains that bad numbers could achieve [short periods](http://scicomp.stackexchange.com/questions/1517/how-can-i-determine-the-period-of-my-pseudo-random-number-generator) on your random numbers. And the longest the period of your random number key, the longer it would take for a brute-force attack to break your encryption. 

I just noticed that Wikipedia [xorshift example](https://en.wikipedia.org/wiki/Xorshift#Example_implementation) uses the exact same numbers as ConfuserEx. You can find [here](http://www.arklyffe.com/main/2010/08/29/xorshift-pseudorandom-number-generator/) some more numbers that provide good random generators, although I guess they are using a different order for the left/right shifting.

Having said that, I guess that even if you choose some "bad numbers" for the shifting operations, I believe you'll still be safe against _script kiddies_, who probably won't use anything more than **ready-made unpackers/deobfuscators**. I mean: even if you choose a bad encryption key, **what are the chances of someone brute-forcing your custom-obfuscator just to decrypt your constants**? 
**I haven't yet seen a deobfuscator doing brute-force**. Probably it would take so long (even if you choose bad numbers) that it wouldn't worth it

PS: Please note that you should change those numbers on **both** [EncodePhase.cs] (https://github.com/yck1509/ConfuserEx/blob/master/Confuser.Protections/Constants/EncodePhase.cs) and [Constant.cs](https://github.com/yck1509/ConfuserEx/blob/master/Confuser.Runtime/Constant.cs).
