### ISSUE TITLE
Name protection

### ISSUE THREAD

**Issue by Praetorian11** [yck1509/ConfuserEx#261]
Hello,
When I switch on Name protection, I get the exception:
Can you help me, please?

Thank you

System.Resources.MissingManifestResourceException: A case-insensitive lookup for resource file "‬‍‌‫‪‭‏⁫‬‮⁬⁬‪⁮⁫‎​‪‎‬⁫‏⁬⁭‏⁮⁬‌⁯‭‫‌‮‏⁫‍‏‍‮‮.pl.resources" in assembly "MagikDT.resources, Version=13.0.99.0, Culture=pl, PublicKeyToken=null" found multiple entries. Remove the duplicates or specify the exact case.
   at System.Resources.ManifestBasedResourceGroveler.CaseInsensitiveManifestResourceStreamLookup(RuntimeAssembly satellite, String name)
   at System.Resources.ManifestBasedResourceGroveler.GetManifestResourceStream(RuntimeAssembly satellite, String fileName, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)

**Comment by XenocodeRCE** [comment]
Mh ... seems like the application you want to protect contains a specific resource, which is not supported or which cause issue

**Comment by Praetorian11** [comment]
It contains strings, images and files. Did you tested with files?

**Comment by XenocodeRCE** [comment]
Yes, and ConfuserEX is fully compatible with every kind of resources ... what option did you selected ? Do you only use ConfuserEX ?

**Comment by Praetorian11** [comment]
Yes, I only use ConfuserEx.
Here is my config

<project outputDir="x:\Project\bin\Release" baseDir="x:\Project\bin\Release" xmlns="http://confuser.codeplex.com">
  <rule pattern="true" inherit="false">
    <protection id="anti ildasm" />
    <protection id="anti tamper" />
    <protection id="constants" />
    <protection id="ctrl flow" />
    <protection id="anti dump" />
    <protection id="anti debug" />
    <protection id="invalid metadata" />
    <protection id="ref proxy" />
    <protection id="resources" />
    <protection id="rename" action="remove" />
  </rule>
  <module path="App.exe">
    <rule pattern="true" />
  </module>
  <module path="en\App.resources.dll">
    <rule pattern="true" />
  </module>
  <module path="sk\App.resources.dll">
    <rule pattern="true" />
  </module>
  <module path="pl\App.resources.dll">
    <rule pattern="true" />
  </module>
</project>

Please notice line
    <protection id="rename" action="remove" />
When I delete action attribute, if fires exception. Otherwise it is ok.

Files are included only in neutral culture, non of the file is localized.
Please don't hesitate to contsact me for the further information, I will be glad to help you.
Thank you.

**Comment by Praetorian11** [comment]
It seems that the xml code was removed, trying next without "<" and ">".
project outputDir="x:\Project\bin\Release" baseDir="x:\Project\bin\Release" xmlns="http://confuser.codeplex.com"
  rule pattern="true" inherit="false"
    protection id="anti ildasm" /
    protection id="anti tamper" /
    protection id="constants" /
    protection id="ctrl flow" /
    protection id="anti dump" /
    protection id="anti debug" /
    protection id="invalid metadata" /
    protection id="ref proxy" /
    protection id="resources" /
    protection id="rename" action="remove" /
  /rule
  module path="App.exe"
    rule pattern="true" /
  /module
  module path="en\App.resources.dll"
    rule pattern="true" /
  /module
  module path="sk\App.resources.dll"
    rule pattern="true" /
  /module
  module path="pl\App.resources.dll"
    rule pattern="true" /
  /module
/project

**Comment by yck1509** [comment]
Hi,
Would it be possible to send the obfuscated output to confuser.net@gmail.com for me to have a look?
