### ISSUE TITLE
Program not working after obfuscation

### ISSUE THREAD

**Issue by yboudjennah** [yck1509/ConfuserEx#262]
Hello

I've tried to obfuscate my application with ConfuserEx (I add the exe + the dlls by drag and drop). Whatever the level of protection I choose, the output exe crashed as soon as I launch it.

I got in the console the following warning : 
[***.dll] SN Key is not provided for a signed module, the output may not be working.

Does anyone have a solution please ?

I thank by advance ;)

**Comment by MurariAlex** [comment]
Which version of ConfuserEx are you using?
Try the latest build at the CI Server: https://ci.appveyor.com/project/yck1509/confuserex/build/artifacts

**Comment by yboudjennah** [comment]
I'm using ConfuserEx v0.5.0 which is the latest stable release.

**Comment by MurariAlex** [comment]
Between the latest stable release and the latest commit made by @yck1509, there are important bug fixes( https://github.com/yck1509/ConfuserEx/compare/v0.5.0...master ) that caused applications to crash. Try the latest build at the CI server.

**Comment by yboudjennah** [comment]
I've got this error now :/

![image](https://cloud.githubusercontent.com/assets/11535296/8349187/185634ae-1b1b-11e5-8217-2597dbaebcd7.png)

**Comment by yboudjennah** [comment]
Nevermind !

It was all because I needed to copy some "App.Config" File in the directory... Silly me ! --'
