### ISSUE TITLE
How does disabling-renaming work in ConfuserEx?

### ISSUE THREAD

**Issue by damotte** [yck1509/ConfuserEx#264]
From other obfuscators we used to prevent renaming a whole class like this:

`[ObfuscationAttribute(Feature = "renaming", ApplyToMembers = true)]`

now with ConfuserEx there seems to be a slightly different syntax. So we tried:

`[ObfuscationAttribute(Exclude = false, Feature = "'Test':-rename")]`

but it didnt work. (Whole class is obfuscated).

What are we missing here?

**Comment by yck1509** [comment]
Hi,
As you could read on [the wiki documentation](https://github.com/yck1509/ConfuserEx/wiki/Declarative-Obfuscation), the correct syntax is:
```C#
[ObfuscationAttribute(Exclude = false, Feature = "-rename")]
class Test {
    ...
}
```

**Comment by damotte** [comment]
thanks, tried that but it still doesnt work.
what exactly is the difference when using `[Obufscation...` and `[ObfuscationAttribute...` ?
could it be the problem, that my class is not in a namespace?
<pre>
[ObfuscationAttribute(Exclude = false, Feature = "-rename")]
static class Program
{
...
}
</pre>

**Comment by yck1509** [comment]
Hi,
The syntax above worked here. Here is my test code:
```C#


[assembly: ObfuscationAttribute(Exclude = false, Feature = "preset(normal)")]

[ObfuscationAttribute(Exclude = false, Feature = "-rename")]
static class Program {
	/// <summary>
	/// The main entry point for the application.
	/// </summary>
	[STAThread]
	static void Main() {
		Application.EnableVisualStyles();
		Application.SetCompatibleTextRenderingDefault(false);
		Application.Run(new Form1());
	}
}
```

**Comment by damotte** [comment]
thanks for your help. i must still be missing something - i have tried every possible combination of Obfuscation and ObfuscationAttribute now. but still this class gets renamed.

could it be my crproj file:
```xml
<pre>
			<project outputDir="." baseDir="outDir" xmlns="http://confuser.codeplex.com">
			  <packer id="compressor" />
			  <module path="Main.exe" />
			</project>
</pre>
```

**Comment by yck1509** [comment]
Hi,
It seems you're using the GUI to protect your application. However, declarative obfuscation(i.e. ObfuscationAttribute) is only supported on the CLI version at the moment. You could read the wiki page I mentioned earlier for usage of the CLI version for declarative obfuscation.

**Comment by damotte** [comment]
thanks.
actually i am using the CLI version like this:

`Confuser.CLI.exe -n obfuscate.crproj -o Main.exe`

**Comment by yck1509** [comment]
Hi,
Currently you can't use crproj formation with ObfuscationAttribute. Instead, you could try:
```
Confuser.CLI.exe -n -o=. Main.exe
```

**Comment by damotte** [comment]
thanks a lot! 
now we made some progress.

i am getting this error:

```
     [exec] [ERROR] Unknown error occurred.
     [exec] Exception: System.ArgumentException: Feature property cannot be set when Exclude is true.
     [exec]    at Confuser.CLI.ObfAttrMarker.<ProcessAttributes>d__0.MoveNext() in c:\projects\confuserex\Confuser.CLI\ObfAttrMarker.cs:line 117
     [exec]    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
     [exec]    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     [exec]    at Confuser.CLI.ObfAttrMarker.ProcessModule(ModuleDefMD module, String snKeyPath, String snKeyPass, List`1 settingAttrs, Dictionary`2 namespaceAttrs) in c:\projects\confuserex\Confuser.CLI\ObfAttrMarker.cs:line 314
     [exec]    at Confuser.CLI.ObfAttrMarker.MarkModule(ModuleDefMD module, Boolean isMain) in c:\projects\confuserex\Confuser.CLI\ObfAttrMarker.cs:line 274
     [exec]    at Confuser.CLI.ObfAttrMarker.MarkProject(ConfuserProject proj, ConfuserContext context) in c:\projects\confuserex\Confuser.CLI\ObfAttrMarker.cs:line 197
     [exec]    at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in c:\projects\confuserex\Confuser.Core\ConfuserEngine.cs:line 135
     [exec] Failed at 12:00 PM, 0:00 elapsed.
```

i guess this is because i have still some other incompatible ObfuscationAttributes from the previous obfuscator in some of my classes. i will see if i can find them now. 

still it would be nice to see in which class this error happened. ;)

**Comment by damotte** [comment]
ok i figured out this last problem but that leads to 2 (rather ridiculous) problems on my side:

1. the output file is actually twice as big as the input file. (with crproj it was about 40% of the size)

2. my virus scanner immediately complains that it contains this virus: https://www.f-secure.com/v-descs/other_w32_generic.shtml

**Comment by yck1509** [comment]
1. You can try adding this line:
```
[assembly: ObfuscationAttribute(Exclude = false, Feature = "packer:compressor")]
```
2. Sorry, but virus scanner tends to detect obfuscated files as malwares. This is out of my ability to solve.

**Comment by damotte** [comment]
thanks!
adding this line leads to:

```
  [exec] Exception: System.ArgumentException: Unexpected end of string in ReadItemName state.
     [exec]    at Confuser.CLI.ObfAttrParser.ParsePackerString(String str, Packer& packer, Dictionary`2& packerParams) in c:\projects\confuserex\Confuser.CLI\ObfAttrParser.cs:line 224
     [exec]    at Confuser.CLI.ObfAttrMarker.MarkModule(ModuleDefMD module, Boolean isMain) in c:\projects\confuserex\Confuser.CLI\ObfAttrMarker.cs:line 235
     [exec]    at Confuser.CLI.ObfAttrMarker.MarkProject(ConfuserProject proj, ConfuserContext context) in c:\projects\confuserex\Confuser.CLI\ObfAttrMarker.cs:line 197
     [exec]    at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in c:\projects\confuserex\Confuser.Core\ConfuserEngine.cs:line 135
```

**Comment by yck1509** [comment]
Oh, I made an mistake, it should be "packer:compressor;".

**Comment by damotte** [comment]
thank you! it works now!
