### ISSUE TITLE
Rename protection

### ISSUE THREAD

**Issue by joker99** [yck1509/ConfuserEx#265]
Is it possible to make ConfuserEX to apply rename protection to all of assemblies specified in project file together?

What I mean, if in assembly A I have public method DoIt(). Assemblies B and C call it. In name protection stage it should be renamed to obfuscated name and calls from assemblies B and C should also be updated.

Currently, public methods are not renamed. If I specify the "renPublic" argument they are renamed but the callers are not updated.

**Comment by bprg** [comment]
This bug has been previously reported, Now not been resolved.

**Comment by yck1509** [comment]
Hi,
I can't reproduce this issue here. It should renames the public members and their reference across the assemblies in project if renPublic is enabled. Maybe try the latest version at [the CI Server](https://ci.appveyor.com/project/yck1509/confuserex)?

**Comment by joker99** [comment]
Sorry, I did not describe the bug correctly. After further investigation the correct bug description is as following

The bug happens only with generic methods. The generic method in the defining assembly gets renamed, but the calling assembly still calls original method and fails with MissingMethod exception.
Example
Dll
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ClassLibrary1
{
    public class Class1
    {
        public string GetString()
        {
            return "Hello";
        }

        public T GetValue<T>(T orig)
        {
            return orig;
        }
    }
}
```
Console App:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ClassLibrary1;

namespace ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Class1 lib = new Class1();
            Console.WriteLine(lib.GetString());
            Console.WriteLine(lib.GetValue(10));
            Console.WriteLine(lib.GetValue("abc"));
        }
    }
}
```

Obfuscation rule
```
    <rule preset="none" pattern="true">
        <protection id="rename">
			<argument name="mode" value="decodable" />
			<argument name="renXaml" value="false" />
			<argument name="renPublic" value="true" />
		</protection>
	</rule>
```
In obfuscated assembly, console app still calls the GetValue<T> method, although it was renamed in referenced assembly to something else.
