### ISSUE TITLE
Output Un-runnable since dnlib update

### ISSUE THREAD

**Issue by MurariAlex** [yck1509/ConfuserEx#272]
Hi,
Since the last commit https://github.com/yck1509/ConfuserEx/commit/a52b37ff853bec30ac715d35c198525a19a8cbda the output of the MahApps.Metro sample is crashing like before, the crproj is the same, with the resources protection and Xaml renaming disabled.

EDIT:
Using TortoiseSVN, I rolled back to commit [1577](https://github.com/yck1509/dnlib/commit/0c3ff294af7563ec63400bb399355c47488fc60b) from your fork of dnlib, recompiled ConfuserEX and everything worked out fine, the output is running fine, so there really is something wrong with the latests commits of dnlib.

```XML
<project outputDir="D:\Projetos\cSharp\Misc\MahApps.Metro\trunk\samples\MetroDemo\bin\NET40\Debug\Confused"
baseDir="D:\Projetos\cSharp\Misc\MahApps.Metro\trunk\samples\MetroDemo\bin\NET40\Debug" xmlns="http://confuser.codeplex.com">
  <rule pattern="true" inherit="false">
    <protection id="anti ildasm" />
    <protection id="anti tamper" action="remove" />
    <protection id="constants"/>
    <protection id="ctrl flow"/>
    <protection id="anti dump" />
    <protection id="anti debug"/>
    <protection id="invalid metadata"/>
    <protection id="ref proxy"/>
    <protection id="resources" action="remove" />
    <protection id="rename">
      <argument name="renXaml" value="false" />
    </protection>
  </rule>
  <module path="MetroDemo.exe" />
  <module path="MahApps.Metro.dll" />
</project>
```

**Comment by MurariAlex** [comment]
BTW, @yck1509, is there a way to prevent an assembly(dll) from being packed with the EXE?
I don't want that all dlls get compressed with the EXE, just some of 'em.

**Comment by yck1509** [comment]
ConfuserEx doesn't support that yet. You could open an issue to request the feature here.
