### ISSUE TITLE
Exclude or Include declarative obfuscation from rule settings

### ISSUE THREAD

**Issue by LiangChow** [yck1509/ConfuserEx#279]
The more obfuscators declarative obfuscation and rules settings is interacting together (e.g Babel obfuscator) but in the ConfuserEx are conflict together, Can you fix the issue ?

**Comment by yck1509** [comment]
Hi,
In general, you should not use multiple obfuscators together, as their protections might be in conflict with each other. In the latest commit, invalid rules would get ignored, you may try that.

**Comment by bprg** [comment]
I have the same problem, I want add a protection to rule then include or exclude with declarative obfuscation, It seems that if adding protection to rule declarative obfuscation not works.

**Comment by LiangChow** [comment]
I tried the latest build not resolved the issue, Please read @bprg comment.

**Comment by bprg** [comment]
After the patch declarative obfuscation not works for example the following syntax exclude all method.
[assembly: Obfuscation(Feature = "+ctrl flow", Exclude = false)]

**Comment by bprg** [comment]
Thank the latest build works, I have another problem, Please try the following code can't exclude two constructor method, Please see the screenshot.

````C#
[assembly: Obfuscation(Feature = "+ctrl flow", Exclude = false)]

namespace NS
{
    [Obfuscation(Feature = "-ctrl flow", Exclude = false)]
    public class Program
    {
        private static void Main(string[] args)
        {

        }

        private void Method1()
        {
        }
    }
}
````

![s](https://cloud.githubusercontent.com/assets/706507/10412572/4264a40a-6f36-11e5-8a91-dc05753ca390.png)

**Comment by yck1509** [comment]
These .ctor/.cctor are not included in Program class, therefore the '-ctrl flow' does not apply to them.

**Comment by bprg** [comment]
You are right but before the patch the two constructor not include.

**Comment by yck1509** [comment]
I suppose the implementation before the patch is incorrect then.
