### ISSUE TITLE
JIT Anti-tamper issue

### ISSUE THREAD

**Issue by MurariAlex** [yck1509/ConfuserEx#281]
Hello,
for some reason, when using JIT anti-tamper, the sample of the MahApps.Metro only displays a white screen instead of showing its content. I'm only applying anti-tamper to the DLL, because if applied to the EXE, the anti-virus detects it as a vírus.

With the normal anti-tamper, everything runs fine.

Here's the CSPROJ, the sample I think you already have it :).

```XML
  <rule pattern="true" inherit="false">
    <protection id="anti tamper" >
	  <argument name="mode" value="jit" />
	  <argument name="key" value="dynamic" />
	</protection>
    <protection id="resources" action="remove" />
    <protection id="rename">
      <argument name="renXaml" value="false" />
    </protection>
  </rule>
  <module path="MahApps.Metro.dll" />
  
  <module path="MetroDemo.exe">
    <rule pattern="true" inherit="false">
    <protection id="anti tamper" action="remove" />
    <protection id="resources" action="remove" />
    <protection id="rename">
      <argument name="renXaml" value="false" />
    </protection>
    </rule>
  </module>
```

**Comment by yck1509** [comment]
Hello,
JIT Anti-Tamper is no longer supported due to massive incompatibility across different version of framework.
