### ISSUE TITLE
Does ConfuserEx support .NET 4.5.x and WPF?

### ISSUE THREAD

**Issue by m5112638** [yck1509/ConfuserEx#285]
My Visual Studio 2013 solution has multiple projects, one executable, a few regular .NET libraries and a few Portable Class Libraries (PCLs), and of course a few third party NuGet packages. I am thinking about using ConfuserEx, and would like to know if ConfuserEx works in such situation (one main executable and many dependencies).

**Comment by atom0s** [comment]
I am using it with .NET 4.6 and WPF no problem,

**Comment by m5112638** [comment]
Thank you atom0s.
