### ISSUE TITLE
Selected assembly packing issue

### ISSUE THREAD

**Issue by kalpesh2804** [yck1509/ConfuserEx#286]
Hi,

I added 1 main module and one supported assembly. that supported assembly located in sub folder. 

I am using ConfuserEx v0.5.0.

Confuser not able to create that sub directory in temp directory and giving error. (Ionic.Zip.Dll originally located in program folder \ SupportedDll)

if we create same name directory in temp directory then its working. 

error screenshot:
![confuser_error](https://cloud.githubusercontent.com/assets/3429717/8683902/0fd53866-2a93-11e5-9963-a42625338e40.png)

**Comment by yck1509** [comment]
Hi,
Please try the latest version at [CI Server](https://ci.appveyor.com/project/yck1509/ConfuserEx), the commit a9894863c5e7d090fea7956b65c864ab6c9d96fd should fix this problem already.

**Comment by kalpesh2804** [comment]
yes, Its fixed in 0.5.0.50

thanks
