### ISSUE TITLE
HRESULT: 0x80020003 (DISP_E_MEMBERNOTFOUND)

### ISSUE THREAD

**Issue by mtgithubmt** [yck1509/ConfuserEx#289]
The Problem:
I have an Excel Addin that I have created with ExcelDNA. I use ConfuserEx to obfuscate my dll. When I double click on a cell in excel and get a COM event callback I get the message HRESULT: 0x80020003 (DISP_E_MEMBERNOTFOUND) when I call range.Value where range is a Range COM object on Excel which I get via the event callback.

I DO NOT get this error when using a non-obfuscated DLL.

Which confuser feature should I disable to get it working?

regards
Michael

**Comment by mtgithubmt** [comment]
I have tried to disable different protections without success. (At least it was not obvious which protections were running or not.)

Would it be possible to get an example of a file that ran no protections against a dll.


My original file was:
            <project outputDir="{0}" baseDir="{1}" debug="true" xmlns="http://confuser.codeplex.com">
              
              <module path="dw.dll">
                    <rule pattern="true" preset="none" inherit="false">
                          <protection id="anti ildasm" action="remove" />
                          <protection id="anti tamper" action="remove"  />
                          <protection id="constants" action="remove"  />
                          <protection id="ctrl flow" action="remove"  />
                          <protection id="anti dump" action="remove"  />
                          
                          <protection id="anti debug" action="remove"  />
                          <protection id="invalid metadata" />
                          <protection id="ref proxy" action="remove"  />
                          <protection id="resources" action="remove"  />
                          
                          
                          
                    </rule>
              </module>
              <module path="dwp.dll">
                    <rule pattern="true" preset="aggressive" inherit="false">
                          <protection id="anti ildasm" />
                          <protection id="anti tamper" />
                          <protection id="constants" />
                          <protection id="ctrl flow" />
                          <protection id="anti dump" />
                          <protection id="anti debug" />
                          <protection id="invalid metadata" />
                          <protection id="ref proxy" />
                          <protection id="resources" />
                          <protection id="rename" />
                    </rule>
              </module>
           </project>   

I tried ...

            <project outputDir="{0}" baseDir="{1}" debug="true" xmlns="http://confuser.codeplex.com">
                  <rule preset="none" pattern="true">

                    </rule>
    
            <rule preset="none" pattern="namespace('dw')">
                    <protection id="anti ildasm" action="remove" />
                    <protection id="anti debug" action="remove" />
                    <protection id="anti dump" action="remove" />
                    <protection id="anti tamper" action="remove" />
                    <protection id="constants" action="remove" />
                    <protection id="ctrl flow" action="remove" />
                    <protection id="invalid metadata" action="remove" />
                    <protection id="ref proxy" action="remove" />
                    <protection id="rename" action="remove" />
                    <protection id="resources" action="remove" />
            </rule>
              <module path="dw.dll">
                <rule preset="none" pattern="false">
                </rule>
              </module>
              <module path="dwp.dll"/>
           </project>

**Comment by mtgithubmt** [comment]
I have fixed this by moving the code that operates against Excel into another file that is not protected. This work fine.

**Comment by yck1509** [comment]
Hi,
I'm not familiar with Excel VBA, but you can try disable renaming on the COM imported Excel interface.
