### ISSUE TITLE
Confuser doesnt obfuscate anything.

### ISSUE THREAD

**Issue by astro-train** [yck1509/ConfuserEx#292]
The probles is that ILspy show exactly code without any changes. Application is using .NET 4.0. What problem it could be? Thank you.

UPD: I've added a rule with gui, and Confuser worked fine, but what should i do with CLI version? There is no example of project file or something in programm's directory.

**Comment by MurariAlex** [comment]
In the CLI you must pass the [project file (CRPOJ)](https://github.com/yck1509/ConfuserEx/blob/master/docs/ProjectFormat.md) as parameter.

The crproj project file is the file that is saved by the GUI.

**Comment by astro-train** [comment]
Thanks! Had little bit hard time, creating this file by my own, lol. I also appreciate that you answered so fast. The problem is solved now. Cheers!
