### ISSUE TITLE
How to exclude a (static) class from being obfuscated?

### ISSUE THREAD

**Issue by m5112638** [yck1509/ConfuserEx#301]
I read through the documentation, and try to figure out how to exclude code from being obfuscated. I am trying something like this:

```
<module path="abc.dll">
    <rule pattern="-the-pattern-to-match-" preset="normal">
        <protection id="rename" action="remove" />
    </rule>
</module>
```
However I am having trouble understand how to use pattern. For the class below
```
namespace X.Y
{
    public static class A
    {
        public static string Text { get { return "test 123"; } }
    }
}
```
What pattern should I use to avoid class A from being obfuscated?

**Comment by atom0s** [comment]
Check out these links, they should help you get what you are asking for:
https://github.com/yck1509/ConfuserEx/wiki/Item-Signatures
https://github.com/yck1509/ConfuserEx/wiki/Declarative-Obfuscation
https://github.com/yck1509/ConfuserEx/blob/master/additional/pdn.crproj

**Comment by m5112638** [comment]
Thank you atom0s. I appreciate your response and help!
