### ISSUE TITLE
Problem to get it work with my c++ app

### ISSUE THREAD

**Issue by romalox456** [yck1509/ConfuserEx#308]
Hi, I have not so much knowledge about obfuscation. i try to obfuscate a c++ project from visual studio 2003 but y get a error. When add the exe file i see Unknow in the description and  when i try to obfuscate i get this error:
![screenshot_1](https://cloud.githubusercontent.com/assets/14005882/9533277/d31bd762-4cda-11e5-8c85-d9801f38d0f2.png)

[ERROR] Unknown error occurred.
Exception: System.BadImageFormatException: .NET data directory RVA is 0
   en dnlib.DotNet.MD.MetaDataCreator.Create(IPEImage peImage, Boolean verify) en E:\Source\Public\Confuser2\dnlib\src\DotNet\MD\MetaDataCreator.cs:línea 185
   en dnlib.DotNet.MD.MetaDataCreator.Load(String fileName) en E:\Source\Public\Confuser2\dnlib\src\DotNet\MD\MetaDataCreator.cs:línea 35
   en dnlib.DotNet.ModuleDefMD.Load(String fileName, ModuleCreationOptions options) en E:\Source\Public\Confuser2\dnlib\src\DotNet\ModuleDefMD.cs:línea 185
   en Confuser.Core.Marker.MarkProject(ConfuserProject proj, ConfuserContext context) en e:\Source\Public\Confuser2\Confuser.Core\Marker.cs:línea 123
   en Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) en e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:línea 122
Failed at 04:41 p.m., 0:00 elapsed.

Thanks in advanced.

**Comment by yck1509** [comment]
Hi,
C/C++ is not supported by ConfuserEx.
