### ISSUE TITLE
Error compiling app in VS2015 if referencing a confused class library

### ISSUE THREAD

**Issue by RobSiklos** [yck1509/ConfuserEx#313]
I made a simple C# class library with one public method and ran confuser on it with only the "invalid metadata protection".

I then made a new C# console application and referenced the obfuscated class library. When I compile my console application in Visual Studio 2015, the build fails with the following error:

> CSC : error CS0009: Metadata file 'C:\Users\robs\Documents\Visual Studio 2015\Projects\SimpleLibrary\bin\Release\Confused\SimpleLibrary.dll' could not be opened -- Illegal tables in compressed metadata stream.

This is bad for us, since we want to ship a class library which is obfuscated, yet still can be referenced by other developers in their apps.

Using ConfuxerEx v0.5.0.

This is my crproj:

```xml
<project outputDir="C:\Users\robs\Documents\Visual Studio 2015\Projects\SimpleLibrary\bin\Release\Confused" baseDir="C:\Users\robs\Documents\Visual Studio 2015\Projects\SimpleLibrary\bin\Release" xmlns="http://confuser.codeplex.com">
  <rule pattern="true" inherit="false">
    <protection id="invalid metadata" />
  </rule>
  <module path="SimpleLibrary.dll" />
</project>
```

**Comment by yck1509** [comment]
Hi,
Invalid metadata may prevent the assembly from loading using Reflection, like in VS. You may try other protections instead.
