### ISSUE TITLE
Files not being confused

### ISSUE THREAD

**Issue by echnaba** [yck1509/ConfuserEx#314]
I'm running Confuser.cli from the command line, and it does not show any errors when confusing a dll.  However, when I use ILSpy to test if the dll can be decompiled, it is instantly decompiled.  When I confuse the same file using the ConfuserEX UI, it cannot be decompiled in ILSpy.
The command I'm running is:
confuser.cli -n -o=(outputDir) fileToConfuse.dll
Is there something I am missing?  I pulled the latest code from the CI server today.
I'm trying to run this from command line so that I can integrate it into a build process.  The dlls need to be copied to different directories after the build.  So I'm trying to avoid writing a crproj file with a hardcoded output directory, and this seemed like a doable dynamic output directory approach.

**Comment by yck1509** [comment]
Hi,
You need to configure ConfuserEx so it knows what protections to apply. You can read the wiki to see how to use ConfuserEx.
