### ISSUE TITLE
Failed to resolve a member

### ISSUE THREAD

**Issue by sbolofsson** [yck1509/ConfuserEx#315]
Hi,

I am experiencing an error when obfuscating a rather simple dll. I am unsure whether the issue lies in dnlib or ConfuserEx. The error can be reproduced as described here:

1. I have created a new empty solution in Visual Studio 2015 following these steps: New Project -> Templates -> Visual C# -> Office/SharePoint -> PowerPoint 2013.

2. I then added a Ribbon: right click on project -> Add New Item -> Ribbon (Visual Designer)

3. Right click on the newly added Ribbon1.cs -> View Code

4. Add this method to the class:

```
    public void ActivateHomeTab()
    {
        RibbonUI.ActivateTabMso("TabHome");
    }
```

5. Build the project and now try to obfuscate the compiled dll, using the normal preset.

6. ConfuserEx will throw the exception:

[ERROR] Failed to resolve a member, check if all dependencies are present in the correct version.
Exception: dnlib.DotNet.MemberRefResolveException: Could not resolve method: Microsoft.Office.Core.IRibbonUI Microsoft.Office.Tools.Ribbon.RibbonBase::get_RibbonUI() 

Things I have tried:
1. Using the latest ConfuserEx build from the CI server as well as the official 0.5.0 release.
2. Tried setting "Embed interop types" to both True and False for the "Microsoft.Office.Interop.PowerPoint" and "Office" references

What I have discovered so far:
It seems like the error lies in the following method in the TypeDef class in dnlib:

public MethodDef FindMethodCheckBaseType(UTF8String name, MethodSig sig, SigComparerOptions options, ModuleDef sourceModule)

which tries to find the RibbonUI property on the Ribbon class. The purpose of this method is to scan all methods in the type definition to find a matching method. It cannot find the method get_RibbonUI due to an error in the comparison of the method signatures.

I don't think the error is especially related to the project being a VSTO addin or the assembly containing the RibbonBase class being a COM assembly.

**Comment by sbolofsson** [comment]
Ok, I managed to get it working. The error was related to the fact that some COM interfaces were defined in multiple assemblies. Even though I disabled embedding of interop types, there existed three interface declarations in the same namespace. Specifically, the Microsoft.Office.Core.IRibbon interface is defined in both:
- Microsoft.Office.Tools.Common.v4.0.Utilities.dll
- Microsoft.Office.Tools.Common.dll
- Office.dll

This caused the method resolution in dnlib to fail.

By changing:

public IMemberForwarded Resolve(MemberRef memberRef) {
    return Resolve(memberRef, 0);
}

to:

public IMemberForwarded Resolve(MemberRef memberRef) {
    return Resolve(memberRef, SigComparerOptions.DontCompareTypeScope);
}

in TypeDef.cs in dnlib, it will not consider modules when comparing type definitions, however, it will still consider namespaces. Another possible solution, which I have not tried though, could be to use the "extern alias" keywords to reference a namespace in a specific assembly.

Furthermore, I also had to disable embedding of interop types, otherwise I experienced a lot of "Unable to cast COM object of type 'System.__ComObject' to interface type ..." errors.

You may consider this issue closed.

**Comment by sbolofsson** [comment]
@yck1509 and @0xd4d on second thoughts, this seems like a bug in either ConfuserEx or dnlib. When developing programs that reference COM libraries it is "normal" that duplicate type declarations exist in different assemblies. Shouldn't dnlib be able to resolve the correct assembly based on the context?

I have tried to look into the code but I can't figure out how it resolves the (incorrect) assembly.

**Comment by yck1509** [comment]
Hi,
Please send me the three dll you listed at confuser.net@gmail.com so that I can look into what went wrong.

**Comment by sbolofsson** [comment]
I've sent you an email.
