### ISSUE TITLE
help with error

### ISSUE THREAD

**Issue by marhex** [yck1509/ConfuserEx#319]
[INFO] ConfuserEx v0.5.0 Copyright (C) Ki 2014
 [INFO] Running on Microsoft Windows NT 6.2.9200.0, .NET Framework v4.0.30319.42000, 64 bits
[DEBUG] Discovering plugins...
 [INFO] Discovered 10 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
[ERROR] Unknown error occurred.
Exception: System.BadImageFormatException: Invalid DOS signature
   à dnlib.PE.ImageDosHeader..ctor(IImageStream reader, Boolean verify) dans E:\Source\Public\Confuser2\dnlib\src\PE\ImageDosHeader.cs:ligne 31
   à dnlib.PE.PEInfo..ctor(IImageStream reader, Boolean verify) dans E:\Source\Public\Confuser2\dnlib\src\PE\PEInfo.cs:ligne 45
   à dnlib.PE.PEImage..ctor(IImageStreamCreator imageStreamCreator, ImageLayout imageLayout, Boolean verify) dans E:\Source\Public\Confuser2\dnlib\src\PE\PEImage.cs:ligne 135
   à dnlib.PE.PEImage..ctor(String fileName, Boolean mapAsImage, Boolean verify) dans E:\Source\Public\Confuser2\dnlib\src\PE\PEImage.cs:ligne 165
   à dnlib.DotNet.MD.MetaDataCreator.Load(String fileName) dans E:\Source\Public\Confuser2\dnlib\src\DotNet\MD\MetaDataCreator.cs:ligne 33
   à Confuser.Core.Marker.MarkProject(ConfuserProject proj, ConfuserContext context) dans e:\Source\Public\Confuser2\Confuser.Core\Marker.cs:ligne 100
   à Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) dans e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:ligne 121
Failed at 23:45, 0:00 elapsed.

**Comment by milsnips** [comment]
same problem here.

**Comment by yck1509** [comment]
Hi,
It seems the input EXE or DLL was corrupted, did you use the correct input file?
