### ISSUE TITLE
ConfuserEx rename 

### ISSUE THREAD

**Issue by NEIINEII** [yck1509/ConfuserEx#324]
Hello guys. How can I change the renaming scheme of confuserEx? I would like obfuscate variables and strings into single characters like the letter 'a' like the Dotfuscator usually does. I'm a newbie to this stuff. thanks!

**Comment by avanpo** [comment]
Have you tried reading the documentation?

https://github.com/yck1509/ConfuserEx/wiki/Name-Protection

**Comment by NEIINEII** [comment]
Yah I already read the documentation but I don't know how to make the confuserEx GUI rename mode to letters as default?

**Comment by avanpo** [comment]
I'm not sure how to do it in the GUI, but if you can edit the .crproj file with a text editor. Within the <rule> block that you are targeting, replace this line

```
<protection id="rename" />
```

with

```
<protection id="rename" mode="letters" />
```

**Comment by yck1509** [comment]
Hi,
As mentioned above, you can change renaming mode using parameters:
```XML
    <protection id="rename" action="add">
        <argument name="mode" value="letters" />
    </protection>
```
