### ISSUE TITLE
SN Key is not provided for a signed module, the output may not be working.

### ISSUE THREAD

**Issue by armaldio** [yck1509/ConfuserEx#325]
Hello, 

Version 0.5.0
Settings compressor

![image](https://cloud.githubusercontent.com/assets/3089715/9828894/f5383ec8-58f4-11e5-9b4b-8b3deb419165.png)

I got this error : SN Key is not provided for a signed module, the output may not be working.

How to solve ?
Thank you

**Comment by yck1509** [comment]
Hi,
You could provide the SN key of the input files to solve the warning.
