### ISSUE TITLE
Cannot confuse single dll?

### ISSUE THREAD

**Issue by CoNFiDeNTHaKaN** [yck1509/ConfuserEx#326]
I am trying to confuse my single dll with the settings below

![image](https://cloud.githubusercontent.com/assets/7744573/9870484/f21784f4-5b94-11e5-998e-089b0936258b.png)

the issue that i have is,

![image](https://cloud.githubusercontent.com/assets/7744573/9870453/9ee25192-5b94-11e5-843f-1161f1c8997c.png)

Can i confuse single dll which has no main()?

**Comment by caverna** [comment]
Yes you can, but you can't use 'compression' (it needs an executable).
Turn it off at the settings page.

**Comment by yck1509** [comment]
Hi,
As mentioned above, packer is not supported for DLL library.
