### ISSUE TITLE
ConfuserEx using Command Line Interface (CLI)

### ISSUE THREAD

**Issue by Gaushick** [yck1509/ConfuserEx#335]
Do we have any documentation for CLI?
or
Any sample syntax?

**Comment by Gaushick** [comment]
I have done the obfuscation using the ConfuserEx from the CLI. Please do the below steps,

1) Download the ConfuserEx from the "https://yck1509.github.io/ConfuserEx/news/index.html"
2) Run the "ConfuserEx.exe" file and try the obfuscation using any dll. Then save the project(*.crproj).
3) Otherwise form the xml syntax like below, and save the file type as (*.crproj).
<project outputDir="D:\bin\Confused" baseDir="D:\bin" xmlns="http://confuser.codeplex.com">
  <rule pattern="true" preset="normal" inherit="false">
    <protection id="anti ildasm" />
    <protection id="anti tamper" />
    <protection id="constants" />
    <protection id="ctrl flow" />
    <protection id="rename" />
    <protection id="anti debug" />
    <protection id="anti dump" action="remove" />
  </rule>
  <module path="System.Mvc.dll" snKey="D:\bin\SN_Key\project.snk" /> 
</project>
4) Open the command prompt, and run the below syntax,
CLI Syntax : confuser.cli -n D:\ConfuserExConfig.crproj

Note :+1: : 
* Run the CLI syntax from the "Confuser.CLI" location.
* Change the configuration according to your project and obfuscate.
* You can learn the configuration changes from the ConfuserEx GUI. (open the (*.crproj)file after save the project)

**Comment by 284247028** [comment]
mark
