### ISSUE TITLE
configuration for unity

### ISSUE THREAD

**Issue by ghiboz** [yck1509/ConfuserEx#349]
Hi!
I wish obfuscate **Assembly-CSharp.dll** generated by unity5..
i've tried different settings and the only set that let's the dll working doesn't obfuscate nothing..
does anybody know which are the settings to obfuscate the dll?
thanks

**Comment by yck1509** [comment]
Hi,
I have no experience with Unity, so I don't know to what extent can the protections work. However, I suppose you can use renaming, ref proxy and constant encryption without major problem.

**Comment by ghiboz** [comment]
thanks! renaming doesn't work, the other yes..
 :+1:
