### ISSUE TITLE
inherits function related exclude rule

### ISSUE THREAD

**Issue by sung17f** [yck1509/ConfuserEx#353]
I want to exclude a field or method of the class that inherits a specific class from the rule.

For example, we have the follow code snippet:

 public class C1 : Parent
{
	public int filed1;
	public int method1();
}

I want to exclude a field1. and rules..

<..rule preset="none" pattern="member-type('field') and inherits('namespace.Parent')">
		<..protection id="rename" action="remove" />
<../rule>

This rule doens't work properly. 
In my quick test, I checked that the inherits() Express Function do this only with the name of classes.
How can I define rule to get it to work like my intention?

Thank you in advance.

**Comment by yck1509** [comment]
The latest build allows `inherits` function to work on members of types. Please try it.

**Comment by sung17f** [comment]
It worked very well. Thanks!!
