### ISSUE TITLE
Memory usage of ConfuserEx

### ISSUE THREAD

**Issue by FRules** [yck1509/ConfuserEx#354]
I created a simple windows service which doesn't do anything more than executing an application on a regular basis and doing a few checks. 
Without using ConfuserEx my RAM Usage is around 6 Mb according to Windows Task Manager.
However, using ConfuserEx in my application increases the usage of memory to around 60 Mb. Here's my .crproj-file I'm using:

```xml
<project baseDir="." outputDir="." xmlns="http://confuser.codeplex.com">
  <rule pattern="true" inherit="false">
    <protection id="rename" />
    <protection id="ctrl flow" />
    <protection id="ref proxy" />
    <protection id="anti debug" />
    <protection id="anti dump" />
    <protection id="constants" />
    <protection id="resources" />
    <protection id="anti tamper" />
  </rule>
  <module path="bin/Release/MyAssembly.exe" />
</project>
```

I think that's a pretty much increase. I wouldn't care if it was around 20 Mb but 60 mb is huge.

Can I do anything to fix that wihout having to ship my assembly without ConfuserEx? I built ConfuserEx from source (hash e4016cc).

**Comment by FRules** [comment]
Extra note: If I remove constants and resources from my crproj-file it's almost the same memory usage of the not obfuscated assembly. Resources-usage is about 24, Constants about 25 Mb. I reproduced this even with a simple "Hello world" C# application. 

Option | Usage of assembly in mb | Single Usage in mb
-------- | ---- |---------------
Without obfuscation | 2.424 | 2.424 
Anti Tamper | 3.136 | 0.712 
Resources | 27.484 | 24.348
Constants | 52.624 | 25.140
Anti dump | 52.776 | 0.152
Anti debug | 52.400 | -0.376
Ref proxy | 52.428 | 0.028
Ctrl flow | 52.608 | 0.180
Rename | 52.420 | -0.188

**Comment by yck1509** [comment]
Hi,
Please try adding a `GC.Collect()` at the beginning of your application. Since Constants and Resources protections extract and decompress a large amount of data, it might cause the memory usage to rise quite a bit.

**Comment by FRules** [comment]
Works, thank you!

**Comment by kresnayoga** [comment]
Hii,
I already add GC.Collect() at app.xaml.cs -> Main at my wpf application. But it not works for me . Could you share how to implement that ?
