### ISSUE TITLE
JITAntiTamper incompatible Win10

### ISSUE THREAD

**Issue by bprg** [yck1509/ConfuserEx#357]
Hi,
I tried the latest version Paint.Net and ILSpy does not run on Win10.

**Comment by yck1509** [comment]
Hi,
AntiTamper JIT mode is no longer supported.

**Comment by LiangChow** [comment]
Most .NET protections using JIT compilation method with the highest compatibility so I do not think is an impossible task, Confuser unpacker easily unpack Normal mode but still JIT mode is strongest. Thanks!
