### ISSUE TITLE
Feature Request: Option for Project-Wide Enum Elements Renaming

### ISSUE THREAD

**Issue by ab-tools** [yck1509/ConfuserEx#363]
I noticed that ConfuserEx does not rename enum elements by default, but with seaching in this issue database (before creating a new issue about it ;-) ) I saw that I can enable it on a per enum basis:
https://github.com/yck1509/ConfuserEx/issues/152

But as I do have a lot enums across the whole project it would be really useful if there would be an option to enable renaming of enum elements for the whole project.

Thanks a lot
Andreas

**Comment by yck1509** [comment]
Hi,

You could use patterns to achieve it: `inherits('System.Enum')`. You can read more about patterns functions at [the wiki](https://github.com/yck1509/ConfuserEx/wiki/Expression-Functions).

**Comment by ab-tools** [comment]
First thanks for your quick reply again!

Just to be sure I understood it correctly, it would be used like this then?

    [assembly: Obfuscation(Exclude = false, Feature = "inherits('System.Enum'):rename(mode=sequential,forceRen=true)")]

Thank you
Andreas

**Comment by yck1509** [comment]
Oops! For now, you can't use patterns with ObfuscationAttributes. If you don't mind modifying the source of ConfuserEx a bit and build it yourself, you can remove the lines 191-192 in \Confuser.Renamer\AnalyzePhase.cs as a workaround.

**Comment by ab-tools** [comment]
Ah, no problem, because I have to build it from source as the latest pre-build version does not work anyway (resulted in lots of exceptions for me).

But it would be great if you would include this work-around into the program itself, of course, that I don't need to remember adding it again in the future. ;-)

But with this work-around my ObfuscationAttribute above is correct?
Just asking as I was not sure if I got the syntax right; didn't need to use these pattern yet. ;-)

**Comment by yck1509** [comment]
ConfuserEx doesn't supports patterns with ObfuscationAttribute yet, so you can't use it like `Feature = "inherits('System.Enum'):rename(mode=sequential,forceRen=true)"`. However, you can use them with crproj files.

**Comment by ab-tools** [comment]
Sorry, but you're confusing me: :-)
you wrote above that I can use it in ObfuscationAttribute when I "remove the lines 191-192 in \Confuser.Renamer\AnalyzePhase.cs as a workaround".

So after doing this change the pattern should work in ObfuscationAttribute, right?

**Comment by yck1509** [comment]
Maybe there is some misunderstanding. ;P
After modifying the source code as described, ConfuserEx would renames all enum elements.

**Comment by ab-tools** [comment]
OK, so I need to do this change to "mix" my other ObfuscationAttributes with the config needed to rename the enums. Now I think I understood it. ;-)

But that's bad as I really would like to keep all things in the project itself without the need of an external configuration file for ConfuserEx. Do you plan to make it possible to use patterns also from ObfuscationAttribute which would be really useful?

Thanks again for your very quick replies
Andreas

**Comment by yck1509** [comment]
I think there is still some misunderstanding. ;P
If you made the change, you don't need to keep a crproj file or adding the pattern to obfuscate enum elements. However if you mean without the change, it is planned to make it able to use patterns with ObfuscationAttribute.

**Comment by ab-tools** [comment]
Ah, I'm really sorry to not get it - now it's clear:
I just do this minor change and then the enums are renamed, without any further config or ObfuscationAttribute needed. ;-)

But looking forward to integration of patterns with ObfuscationAttribute!

Thanks again
Andreas

**Comment by ab-tools** [comment]
Just as I saw you did a lot commits to this project in the past month:
is the manual source code change in the "AnalyzePhase.cs" file (see above) still needed for enum renames to work or is that already implemented in ConfuserEx itself in the meantime?

**Comment by yck1509** [comment]
As of the latest builds, you can now use patterns in ObfuscationAttributes, so you can do like:
```C#
[assembly: Obfuscation(Exclude = false, Feature = "is-type('enum'):rename(mode=sequential,forceRen=true)")]
```

**Comment by ab-tools** [comment]
Hm, basically I don't want to "force" the rename of all enums skipping the detection of "problematic enum renaming" which are my faults and need to be fixed by me first (like it was the case for issue #364).

Therefore I just want that enums are renamed "normally" if ConfuserEx does not detect a reason why they should not be renamed.

This works fine after I removed the two lines from the source code manually like you explained above, but without doing that (just checked that again) also the latest ConfuserEx source code version does not rename the enums at all which I would expect if "rename" is used.

This would be great if it would get fixed.
Although I can work-around this bug by removing these two source code lines above, I would really like to get rid of this work-around (as I'm concerned that I forget it somewhen and all enums stay un-renamed)...

**Comment by yck1509** [comment]
By default, ConfuserEx only excludes enum elements from renaming, while the enum type itself might still be renamed. If enum elements are no longer excluded from renaming, it might break some application that uses ConfuserEx, so I don't think it's a good idea to change the default behavior at the moment.

**Comment by ab-tools** [comment]
Thanks for your reply again!

But it would be great than if you could add an option to change this default behavior as currently the only way is to remove these two code lines manually to have the functionality:
"rename enum elements if no problematic enum usage is found"

Because if I use the "is-type('enum'):rename(mode=sequential,forceRen=true)" condition it will rename the enums in any case also if it finds "problematic enum usage".

Therefore currently the only way to get enums including their elements renamed (but only if no "problematic enum usage" has been found) is to change the source code which seems not to be a very clean solution.

**Comment by ab-tools** [comment]
OK, great, thank you!

So I just need to add this "renEnum=true" parameter here, right?

    [assembly: Obfuscation(Exclude = false, Feature = "inherits('System.Enum'):rename(mode=sequential,renEnum=true)")]
