### ISSUE TITLE
Version Bump

### ISSUE THREAD

**Issue by MurariAlex** [yck1509/ConfuserEx#366]
Hi, Ki!

This is not an issue, but a sugestion - I believe that many issues being reported here have already been addressed and fixed in the last commits, but the release section is extremely outdated, and people usually don't even bother to download the binaries from the CI server, so they take it from the release section.
Even if your're not planning to bump a major/minor version of ConfuserEx, a bug fix version bump (0.5.1, for example) will do some good and halt the misleading. Of course, if you're gonna bump the minor version soon (which means new features) that will be even better and worth waiting. 

Alex

**Comment by yck1509** [comment]
I'll do it when I got time to do so... :P

**Comment by MurariAlex** [comment]
Well, guess that wasn't so hard. 
Good job. :)
