### ISSUE TITLE
Variables Not Being Renamed

### ISSUE THREAD

**Issue by MurariAlex** [yck1509/ConfuserEx#370]
Hi,
Here we go again.

Some local variables are not being renamed in public methods in class libraries.
This is an boolean variable example:

```csharp
    public class SomeClass
    {
        public bool IsValid()
        {
            var isValid = DateTime.Compare(new DateTime(), new DateTime()) > 0;

            return isValid;
        }
    }
```

Browsing with dnSpy, the isValid variable is there, mangled by the CF but untouched. The crproj has all the renaming settings enabled and the ConfuserEx is the latest.

Thanks.

**Comment by yck1509** [comment]
Hi,
The variable names are stored in PDB files. Most likely you did not remove the PDB files and dnSpy read from it.

**Comment by MurariAlex** [comment]
Yep, you're right. Removed the PDB file and the variable names became generic (result, flag)...
There's nothing to do to prevent the real local variable names from being stored in the PDB?

**Comment by yck1509** [comment]
Usually PDB should not be shipped with the application, as it contains many internal information. However if you want, you can use the renPdb parameter to encrypt the variable names in PDB.

**Comment by MurariAlex** [comment]
That's great, gonna test it... :)
I don't like shipping the PDB file with the application too... but sometimes I need more detailed exception information (like line numbers and stack trace) and it's only possible with PDB. And most errors only occur in the client environment... everything always works fine in the dev machine :P

**Comment by MurariAlex** [comment]
renPdb did the job! That's great!
Thanks, Ki!
