### ISSUE TITLE
Numeric Constants not Encoded

### ISSUE THREAD

**Issue by ab-tools** [yck1509/ConfuserEx#373]
While still testing the obfuscation of ConfuserEx I noticed that not all constants are encoded.

Here is a small example project to show the issue:
http://www.ab-tools.com/temp/ConfuserTest1.zip

As you can see I've used the obfuscation option "constants(elements=SNPI)" for testing which should really encode all constants.

Then in the code I've defined following constant strings (not as "real" constants, but just as "realonly" string that ConfuserEx is able to change them):

	private readonly string STRING_CONSTANT_TEST = "test";
	private readonly int INT_CONSTANT_TEST = 716417;
	private readonly double DOUBLE_CONSTANT_TEST = 3.45752;
	private readonly int PRIMITIVE_CONSTANT_TEST = 1;

As you can see in the obfuscated assembly the first constant (the string type one) is encoded just fine, but none of the other 3 - it looks like this after obfuscation:

    private readonly string B = <Module> . <string>(2429719518U);
    private readonly int c = 716417;
    private readonly double C = 3.45752;
    private readonly int d = 1;

What is the reason for that?

Thank you
Andreas

**Comment by yck1509** [comment]
Hi,
Please try using the following settings with the latest build (order is important):
```C#
[assembly: Obfuscation(Exclude = false, Feature = "anti debug;anti ildasm;constants(elements=SNPI);rename(mode=sequential)")]
[assembly: Obfuscation(Exclude = false, Feature = "namespace('ConfuserTest1.Serialize'):-rename")]
```

**Comment by ab-tools** [comment]
Also this works fine now, thanks!
