### ISSUE TITLE
Renaming Class/Type Names, but not its Members

### ISSUE THREAD

**Issue by ab-tools** [yck1509/ConfuserEx#374]
Sorry to bother you once more, but I've got one more question.

I'm using a lot serialization (a "protobuf-net" clone) in my project for data exchange or just for saving data and settings. Therefore, to not break the serialization with obfuscation the types (classes names) and also the namespace names involved in serialization all need to stay the same. But as all class members which should be included in serialization get a serialization member attribute with a unique ID anyway, it is not a problem to rename all these class members.

Therefore I would like to configure ConfuserEx to exclude all sub-namespaces and class names from a certain namespace which I can do like this:

    [assembly: Obfuscation(Exclude = false, Feature = "namespace 'ConfuserTest1.Serialize':-rename")]

But now I need all class members (properties, variables, functions, ...) in this namespace and below to be included in obfuscation again.

Of course, I know I can do that by adding a

    [Obfuscation(Exclude = false, Feature = "rename(mode=sequential)")]

to every single class member I want to be included again like I did in this example project:
http://www.ab-tools.com/temp/ConfuserTest1.zip
That works, but this would be a lot of work (there are hundreds of them!) and also really "deface" the code with so many attributes.

Is there a way to define a namespace/class rename exclusion which is not inherited by its members?
Then I would just need to add exclusion attributes to all classes involved and their class members would still be obfuscated.

Or what is the best way to accomplish this?

Thanks again a lot in advance for your great support
Andreas

**Comment by ab-tools** [comment]
Ah, just found this

    ApplyToMembers: The children uses this protection settings as base.
    Exclude: No protection will be applied to this item.
    !ApplyToMembers + !Exclude: The protection settings just apply to this item.
    ApplyToMembers + Exclude: This item and its chilren will have no protection.	

now here accidentally:
https://github.com/yck1509/ConfuserEx/blob/master/docs/DeclarativeObfuscation.txt

So I guess it's possible as I wrote above - I'll try it now.

Sorry for not not seeing this before posting, but I checked in the Wiki and didn't find any documentation about this there. Maybe you could add it there as well as this probably would prevent some unnecessary questions like this. ;-)

Thanks anyway
Andreas

**Comment by ab-tools** [comment]
Hm, this "ApplyToMembers" option at least seems not to do work as I would expect it to do.

Here is one example
http://www.ab-tools.com/temp/ConfuserTest1.zip
where I used this:

    [assembly: Obfuscation(Exclude = false, ApplyToMembers = false, Feature = "namespace 'ConfuserTest1.Serialize':-rename")]

The result is that it renames just everything INCLUDING the namespace "ConfuserTest1.Serialize".

Then I tried to use

    [assembly: Obfuscation(Exclude = false, ApplyToMembers = true, Feature = "namespace 'ConfuserTest1.Serialize':-rename")]

but now it renames ONLY the namespace "ConfuserTest1.Serialize" including the classes and members, but not the namespaces "ConfuserTest1.Serialize.Data1" and "ConfuserTest1.Serialize.Data2" with their members which I would expect if "ApplyToMembers = true" is used.

Do I missunderstand this "ApplyToMembers" option?

Thank you
Andreas

**Comment by yck1509** [comment]
Hi,
Please try using the following settings with the latest build (order is important):
```C#
[assembly: Obfuscation(Exclude = false, Feature = "anti debug;anti ildasm;constants(elements=SNPI);rename(mode=sequential)")]
[assembly: Obfuscation(Exclude = false, ApplyToMembers = false, Feature = "match('^ConfuserTest1.Serialize.') and member-type('type'):-rename")]
```

**Comment by ab-tools** [comment]
Just wanted to thanks you for the great support again!

It works without problems this way with the latest source code version.

**Comment by ab-tools** [comment]
Unfortunately I closed this issue too early:
although it works fine now in a simple case like your example, it still does not work as expected in more complex cases.

Here is another example project showing the problem:
http://www.ab-tools.com/temp/ConfuserTest3.zip

As you can see there are 4 namespace now:

    namespace ConfuserTest1.Serialize.Data1
    namespace ConfuserTest1.Serialize.Data2
    namespace ConfuserTest1.Serialize.Data3
    namespace ConfuserTest1.Serialize.Data4

And I'm using following attributes:

    [assembly: Obfuscation(Exclude = false, Feature = "anti debug;anti ildasm;constants(elements=SNPI);rename(mode=sequential)")]
    [assembly: Obfuscation(Exclude = false, ApplyToMembers = false, Feature = "match('^ConfuserTest1.Serialize.Data1.') and member-type('type'):-rename")]
    [assembly: Obfuscation(Exclude = false, ApplyToMembers = false, Feature = "match('^ConfuserTest1.Serialize.Data2.') and member-type('type'):-rename")]
    [assembly: Obfuscation(Exclude = false, ApplyToMembers = false, Feature = "match('^ConfuserTest1.Serialize.Data3.') and member-type('type'):-rename")]
    [assembly: Obfuscation(Exclude = false, ApplyToMembers = false, Feature = "match('^ConfuserTest1.Serialize.Data4.') and member-type('type'):-rename")]

The result is this (only two of name spaces are preserved):
![confuserexrename2](https://cloud.githubusercontent.com/assets/1347603/11868800/cfa54d9c-a4ba-11e5-811a-ee707cca9725.png)

Of course, I know that for this specific case I could just preserve "ConfuserTest1.Serialize" itself, but this example is only to show you that using multiple "match" clauses obviously do not work correctly.

Best regards and thanks in advance
Andreas

**Comment by yck1509** [comment]
Hi,
It seems I made a wrong assumption in ordering of custom attributes. Please use the latest commit, along with the following configuration:
```C#
[assembly: Obfuscation(Exclude = false, Feature = "1. anti debug;anti ildasm;constants(elements=SNPI);rename(mode=sequential)")]
[assembly: Obfuscation(Exclude = false, ApplyToMembers = false, Feature = "2. match('^ConfuserTest1.Serialize.Data1.') and member-type('type'):-rename")]
[assembly: Obfuscation(Exclude = false, ApplyToMembers = false, Feature = "3. match('^ConfuserTest1.Serialize.Data2.') and member-type('type'):-rename")]
[assembly: Obfuscation(Exclude = false, ApplyToMembers = false, Feature = "4. match('^ConfuserTest1.Serialize.Data3.') and member-type('type'):-rename")]
[assembly: Obfuscation(Exclude = false, ApplyToMembers = false, Feature = "5. match('^ConfuserTest1.Serialize.Data4.') and member-type('type'):-rename")]
```

**Comment by ab-tools** [comment]
Thanks a lot - this looks very good now with the latest source code and the configuration above!

I'll reopen the issue in case I should find a problem again, but first test (also in the "real" project) were all successful. :-)

Thanks again for your great support!
After the project has been released successfully with ConfuserEx obfuscation I will definitely consider a donation for you.

**Comment by devTime02017** [comment]
Hi.
Testing with code ConfuserTest2.zip from @ab-tools ,  the solution from @yck1509  commented on 6 Dec 2015, don´t work for me on ConfuserEx version 1.0.0.0: all namespace, members are renamed, except Element1, Element2, Element3. 



`
[assembly: Obfuscation(Exclude = false, Feature = "anti debug;anti ildasm;constants(elements=SNPI);rename(mode=sequential)")]
`
`[assembly: Obfuscation(Exclude = false, ApplyToMembers = false, Feature = "match('^ConfuserTest1.Serialize') and member-type('type'):-rename")]
`

[dnSpy decompiler image sample](https://drive.google.com/open?id=0B4tWBxV1jhvZWXY0OVpwS05HT1U)

Can you help me?

**Comment by ab-tools** [comment]
Hello devTime02017,

yes, I can confirm that the latest ConfuserEx version introduced some incompatibilities again (for whatever reasons).

Therefore we just stayed with an older version which we customized a bit:
That works fine for us.

Best regards
Andreas
