### ISSUE TITLE
AntiDump doesn't work with FW4.5 - FW4.5.1 - FW4.5.2 - FW4.6

### ISSUE THREAD

**Issue by bprg** [yck1509/ConfuserEx#383]
Hi Ki,
I'm trying on Windows10 x64.

**Comment by yck1509** [comment]
It's working here, do you have any sample of it?

**Comment by bprg** [comment]
Please try the assemblies.
https://www.dropbox.com/s/0hrjde0l1j4vyl6/Confused.rar?dl=0

**Comment by yck1509** [comment]
Should be fixed by a4a885680f6fdf2325f3d50a078df71c8ba7343b
