### ISSUE TITLE
Windows 8.1 compatibility

### ISSUE THREAD

**Issue by adisapir** [yck1509/ConfuserEx#39]
Using ConfuserEx for some of my dll's, I've noticed that while the app runs well on my windows 7/server machines, it fails to run on various Windows 8.1 machines.

The raised exception is appears scrambled.
Anyone else experienced this issue?

To see the error (if you're running Windows 8) - try installing this: http://www.doccolabs.com/download/download_sqltablezip.html

**Comment by Snoelk** [comment]
this problem still occurs when you protect your assembly with maximum settings. on window 7 it will run perfect and under windows 8.1 it just crashes. not sure whats the difference between agressive and maximum

**Comment by js35** [comment]
I confirm there is still a problem. I have an app with DLL's launching correctly on Windows 7 and not launching on Windows 8.1. Settings are Preset: maximum; Protections: all.

It launches correctly on Windows 8.1 when I remove anti dump. I can provide an exe if it helps.
