### ISSUE TITLE
How to compile this project from github source?

### ISSUE THREAD

**Issue by uGiFarukh** [yck1509/ConfuserEx#398]
Hello,

How can I compile this whole ConfuserEx2 project from the latest github source code? I tried compiling it with Visual Studio 2015 Update 1 but it failed and have many errors and warnings. Can anyone please tell me how to simply compile this project in Visual Studio without any problem?

Thanks in advance...

**Comment by caverna** [comment]
I didn't have any problem compiling the source at VS2015. The project doesn't have any "mysterious" dependecies...
After a little project upgrade, everything behaves as expected.
Try to compile my fork and see if it works.

**Comment by mrkcur** [comment]
You may have to get yck1509's custom version of dnlib.  I manually downloaded this project, added it to the solution, then did "add reference" to all the existing projects in the solution.  Then all my build errors went away.

https://github.com/yck1509/dnlib

**Comment by uGiFarukh** [comment]
Got it....thanks man...that solved the problem....
