### ISSUE TITLE
System.BadImageFormatException: Could not load file or assembly 'XXX' or one of its dependencies. The module was expected to contain an assembly manifest.

### ISSUE THREAD

**Issue by asianati** [yck1509/ConfuserEx#402]
Hi,

I have a project which uses reflection to find all referenced assemblies in the main app exe file:
Assembly theAssembly= theAssembly = Assembly.ReflectionOnlyLoad(referenceAssemblyfullName);

this code works without any problem if the assemblies are not obfuscated, but after obfuscating the assemblies, I got this exception:
System.BadImageFormatException: Could not load file or assembly 'XXX' or one of its dependencies. The module was expected to contain an assembly manifest.

How can I fix this issue?
Thanks

ConfuserEx v0.6.0 is used
Protection settings: Presets to maximum, No Meta data protection, No resource protection, no name protection

**Comment by yck1509** [comment]
Hi,
You may want to try aggressive preset instead. Maximum preset tends to cause some incompatibility with reflection.

**Comment by asianati** [comment]
Thanks. It solved the problem
