### ISSUE TITLE
Constants protection return value bug with doubles but not floats

### ISSUE THREAD

**Issue by yehatest** [yck1509/ConfuserEx#409]
When protecting a double the returned value is not the original one. Is easy testable by doing this:

    double d = 100.0;
    Console.WriteLine(d);

You need to enable number protection under constants:

    <protection id="constants">
        <argument name="elements" value="SNPI" />
    </protection>

**Comment by XODE0** [comment]
it is because of this
https://github.com/yck1509/ConfuserEx/commit/5f19e93e730fa6b25ddb3cf15636f1c397be1ad6

and already montioned here 
https://github.com/yck1509/ConfuserEx/issues/387

**Comment by yehatest** [comment]
Nice. Have not searched closed issues. Thank you.

**Comment by yck1509** [comment]
Hi,
It should be fixed by the mentioned commit. If your problem remains, please say so.
