### ISSUE TITLE
Confuser.Runtime Compressor.cs Failed to resolve dependency

### ISSUE THREAD

**Issue by stormbuddy** [yck1509/ConfuserEx#410]
I'm trying to add a splash screen that shows up during unpacking because it takes really long on some older CPUs. If I add using System.Drawing; to Compressor.cs and place the code below at top of Main method (Entry point) of Compressor.cs I get the error "Unresolved Dependency".

    byte [] test = new byte[] { 1,1,1,1};
    var form = new Form();
    form.BackgroundImage = new Bitmap(new MemoryStream(test));
    form.Show();

**Comment by yck1509** [comment]
Hi,
If you use initializers like "new byte[] { 1, 2, 3, 4 }", compiler would insert some code that does not get added to the output. I would suggest you to use base64 encoding and use Convert.FromBase64String instead.

**Comment by stormbuddy** [comment]
Nope, still doesn't work, getting the same error
 [ERROR] Failed to resolve dependency of Confuser.Runtime 'WindowsFormsApplication1.exe'.
Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: Confuser.Runtime,

**Comment by finndev** [comment]
You have to put your code in its own method to get the dependencies automatically added. It seems that you currently have your code in the Main() Method.

**Comment by stormbuddy** [comment]
Oh thank you! Works now. Silly me haha! ^_^
