### ISSUE TITLE
Override of methods in generic types obfuscated incorrectly

### ISSUE THREAD

**Issue by ivan-danilov** [yck1509/ConfuserEx#413]
As I have found in https://github.com/yck1509/ConfuserEx/issues/405#issuecomment-171063578 `.override` directive references plain name of base class at least in some cases.

**Comment by yck1509** [comment]
Hi,
Do you have an example that demonstrate the issue you fixed?

**Comment by ivan-danilov** [comment]
I certainly do, but I can't share it. Will try to make minimal reproduction and post here.

**Comment by ivan-danilov** [comment]
If I leave only the classes present in the inheritance hierarchy where issue occurs - problem disappears :(
I have requested permission to share the library with you privately, but not sure I'd get it. I think I can share obfuscated variant with you, but don't see how it might help.

Under debug I was seeing `baseSlot.MethodDef.Name` was `Install`, while in the base class it was already obfuscated to `2`. Thus I've came up with 32fdf50485b52c160c59dee0c465ce27484b5b55 (not mentioned in this issue, but it is in the related PR #414).
With the latest sources for some reason `baseSlot.MethodDef.Name` is `2` as it should be, but `thisSlot.Signature` still contains `Install` (at least it is the only place where I can found the name now). And in the result assembly the following is generated:
```
.class public auto ansi beforefieldinit bE<'\u0001'>
	extends class LdA<!'\u0001'>
{
// ... ... ... ...
.method family hidebysig virtual 
	instance class [mscorlib]System.Collections.Generic.IList`1<class AC> '2' (
		!'\u0001' ''
	) cil managed 
{
	.override method instance class [mscorlib]System.Collections.Generic.IList`1<class AC> class LdA<!'\u0001'>::Install(!0)
```

Base class looks like this:
```
.class public auto ansi abstract beforefieldinit LdA<'\u0001'>
	extends [mscorlib]System.Object
{
// ... ... ... ...
	.method family hidebysig newslot abstract virtual 
		instance class [mscorlib]System.Collections.Generic.IList`1<class AC> '2' (
			!'\u0001' ''
		) cil managed 
	{
		.custom instance void pA::.ctor() = (
			01 00 00 00
		)
	} // end of method LdA::'2'
```

`pA` is `NotNullAttribute`, so nothing important.

**Comment by ivan-danilov** [comment]
Sorry for the confusion, it is still `Install` even in the latest code in `baseSlot.MethodDef.Name` in the `OverrideDirectiveReference.UpdateNameReference` method (I've just mistyped the word thus breakpoint hadn't worked correctly when it should).
