### ISSUE TITLE
Rename obfuscation rule breaks inherited virtual methods(WinRT)

### ISSUE THREAD

**Issue by altk** [yck1509/ConfuserEx#417]
```
<rule pattern="true">
  <protection id="rename">
    <argument name="mode" value="debug" />
  </protection>
</rule>
```
```
internal sealed class SomeClass : Grid
{
   protected override Size MeasureOverride(Size availableSize){...}
}
```
After obfuscation method is renamed to _MeasureOverride.

**Comment by altk** [comment]
Another example of incorrect renaming:
'''
public override int _GetHashCode()...
public override bool _Equals(object obj)...
'''

**Comment by nlips** [comment]
This is not a bug.
The **debug** mode is precisely to rename the functions by **adding the prefix "_"**!

**Comment by altk** [comment]
Is rename overriding methods not a bug, really? GetHashCode and Equals inherited methods. Obfuscator should not rename them.

**Comment by eaba** [comment]
Kindly try this:
<protection id="rename">
        <argument name="mode" value="letters" />
</protection>

**Comment by yck1509** [comment]
Hi,
Debug mode is not intended for use. ConfuserEx uses special technique that allows inherited methods to be renamed.

**Comment by altk** [comment]
I use debug mode only for viewing a renamed methods.
For demonstrating issues I created project and published it on GitHub:
https://github.com/altk/ConfuserExErrors
If you delete/comment
```
<rule pattern="match-type-name('.*`1') and member-type('method')" inherit="true">
  <protection id="rename" action="remove" />
</rule>
```
or
```
<rule pattern="name('MeasureOverride')" inherit="true">
  <protection id="rename" action="remove" />
</rule>
```
You will see fail of compilation Win10 Release x86/x64/ARM application project or Test2 fail.

**Comment by altk** [comment]
3 weeks had passed...

**Comment by yck1509** [comment]
Sorry for the late response, I just got VS 2015 installed to test your sample. For some reason I could not compile the Win10 version so I tested using WP8 version. Please try if it fixes your issue.
