### ISSUE TITLE
How to declare class wich don't take effect of renameing?

### ISSUE THREAD

**Issue by VOCCTQ** [yck1509/ConfuserEx#420]
How to declare class wich don't take effect of renameing? I cant find any information about this... it is possible?  Because serialisation dont work if it will be renamed.

Thanks!

**Comment by yck1509** [comment]
Hi,
You can use `[Obfuscation(Feature = "-rename", Excluded = false)]` to exclude it from renaming in C#.

**Comment by VOCCTQ** [comment]
Thanks it works like a charm - very good work!
