### ISSUE TITLE
Can't create AppDomain after Obfuscation

### ISSUE THREAD

**Issue by cdrcools** [yck1509/ConfuserEx#423]
Hi I'm getting BadImageFormatException when I run my program after obfuscation
using the following protections anti-tamper, anti-dump also the packer.
It works if i remove these protections.
heres a snippet of my code:

            var dmType = typeof(DomainManager);
            var setup = new AppDomainSetup
            {
                AppDomainManagerAssembly = Assembly.GetExecutingAssembly().FullName,
                AppDomainManagerType = dmType.FullName
            };
            var domain = AppDomain.CreateDomain("OtherDomain", null, setup);
            domain.AssemblyResolve += CurrentDomain_AssemblyResolve;
            domain.DoCallBack(InternalLoader);

**Comment by yck1509** [comment]
Anti Dump would interfere with Reflection, which AppDomain creation would use. Try disabling it.

**Comment by cdrcools** [comment]
Thanks for getting back, as I mentioned in my previous post removing those protections allows it to work, I was hoping there was a bug-fix available or some sort of work-around so I can apply all protections. Anyway keep up the good work this project is awesome
