### ISSUE TITLE
Can Confuser modify algorithm?

### ISSUE THREAD

**Issue by uniqmr** [yck1509/ConfuserEx#441]
Dear Sir, Thank you for your great effort.

I have an Accounting Software and I use ConfuserEx. So far I have checked, everything is working well. 

My software has many complex calculations. Is there any remote chance, that, ConfuserEx could modify the calculation algorithm/logic to cause wrong year end data (balance sheet)?

Just a funny thought, please reply....

**Comment by yck1509** [comment]
Hi,
If ConfuserEx is working correctly, there would be no way that the algorithm of your application would modified in a wrong way.

**Comment by uniqmr** [comment]
Thanks a lot again.
