### ISSUE TITLE
ctrl flow mangles boilerplate form code

### ISSUE THREAD

**Issue by LaraSQP** [yck1509/ConfuserEx#446]
I have an application with a button that does nothing. If obfuscated with max on all protections, the application crashes when calling PerformClick() on that button:

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.InvalidProgramException: Common Language Runtime detected an invalid program.
>    at ⁫⁯‌‍​‌⁪‎‫‍​⁪‌‌‍⁪​‏‌⁮‪‌‭‎⁯‌‏‭‮⁫‬⁫⁭​‫‍⁭⁮⁬⁫‮.⁬⁭‮‎‌‫⁪​⁬⁮‏⁯⁮⁫‮⁮‭​⁬‏⁬‬⁪‮‪‪‫​‮‪⁫⁫‌⁮⁫⁮⁪⁬‭‌‮(Object , EventArgs )
>    at System.Windows.Forms.Control.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.PerformClick()
>    at ⁫⁯‌‍​‌⁪‎‫‍​⁪‌‌‍⁪​‏‌⁮‪‌‭‎⁯‌‏‭‮⁫‬⁫⁭​‫‍⁭⁮⁬⁫‮.⁭⁫‎‪⁯⁪‍⁯‬‏‪‭⁭‎‎⁭‏‍​‏⁫​⁯‏⁭⁯‎‬​⁯⁪⁮⁫‌‮‎‬⁯⁭‫‮(String , Boolean )
>    at ‫‍‫‌⁪⁮‬‫‭⁯​‭‌⁯‮⁭⁪‎‬⁭​‭‮⁪‍⁯‬‭‏⁪⁮‭‫‍⁬‌‏‬⁫‍‮.⁭⁫‎‪⁯⁪‍⁯‬‏‪‭⁭‎‎⁭‏‍​‏⁫​⁯‏⁭⁯‎‬​⁯⁪⁮⁫‌‮‎‬⁯⁭‫‮(String , Boolean )
>    at ‮​⁭⁮‬‫⁮‌‬‪⁪‌⁭⁯‍‬‍​⁭‫‪‍⁯⁭⁫⁯‎​⁬​⁬⁯⁪‭‬‍‬⁯⁭⁬‮.⁭‌‪‍⁬⁯​⁬‎‭​‪⁭⁭‮​⁫‏‍⁮⁭‫‎⁪⁭‪‍⁮‎⁪‎‬‫‎‮⁫‌‫‭‭‮()
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1055.0 built by: NETFXREL2
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
> ----------------------------------------
> MyApp
>     Assembly Version: 1.0.0.0
>     Win32 Version: 1.0.0.0
>     CodeBase: file:///D:/MyApp/bin/Release/Confused/MyApp.exe
> ----------------------------------------
> NnLBOVDyILabKWtTTBnAKHuGCTDp
>     Assembly Version: 0.0.0.0
>     Win32 Version: 1.0.0.0
>     CodeBase: file:///D:/MyApp/bin/Release/Confused/MyApp.exe
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1055.0 built by: NETFXREL2
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1055.0 built by: NETFXREL2
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1055.0 built by: NETFXREL2
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1055.0 built by: NETFXREL2
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1055.0 built by: NETFXREL2
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1055.0 built by: NETFXREL2
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> System.Speech
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1055.0 built by: NETFXREL2
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Speech/v4.0_4.0.0.0__31bf3856ad364e35/System.Speech.dll
> ----------------------------------------
> System.Management
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.6.1055.0 built by: NETFXREL2
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
> ----------------------------------------

Removing the ctrl flow protection removes the problem. There is nothing special about this button other than it is on a user control.

A more verbose exception is given if the button is simply clicked on:

> System.InvalidProgramException: Common Language Runtime detected an invalid program.
>    at ⁫⁯‌‍​‌⁪‎‫‍​⁪‌‌‍⁪​‏‌⁮‪‌‭‎⁯‌‏‭‮⁫‬⁫⁭​‫‍⁭⁮⁬⁫‮.⁬⁭‮‎‌‫⁪​⁬⁮‏⁯⁮⁫‮⁮‭​⁬‏⁬‬⁪‮‪‪‫​‮‪⁫⁫‌⁮⁫⁮⁪⁬‭‌‮(Object , EventArgs )
>    at System.Windows.Forms.Control.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.PerformClick()
>    at ⁬‪⁪‌⁪‫⁮‪‍⁮⁬‪‮⁭‎⁫⁭‏‍‪‌⁬‏⁪​⁭‍‫⁮‌‫‍‮⁮⁯‍‬⁬​⁮‮.⁫‭​⁯‭⁯‭⁬‎‪⁫‌‍⁮‍⁮⁪⁯‬⁮‌⁮‫⁯⁬⁫​‮⁭‌⁭‬‬‍⁯⁮⁪⁬‎‌‮(Object , KeyEventArgs )
>    at System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
>    at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
>    at System.Windows.Forms.Control.WmKeyChar(Message& m)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.TextBox.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Using ConfuserEx 0.6.0

Let me know if you need more details.

**Comment by LaraSQP** [comment]
I have now removed all protections except for ctrl flow. The app triggers the same exception shown above. Any clues will be appreciated.

**Comment by yck1509** [comment]
Hi,
Do you have any sample that could be shared so that I could reproduce the issue?

**Comment by LaraSQP** [comment]
Thanks for the quick reply.

I searched through the code and the error pops elsewhere. So it is not related to boilerplate code as I thought.

Attach is some code that crashes the app and busts ILSpy and JustDecompile. I've only used the ctrl flow protection on it.

[code.txt](https://github.com/yck1509/ConfuserEx/files/160212/code.txt)

**Comment by yck1509** [comment]
Hi,
Please use the latest version at the [CI Server](ci.appveyor.com/project/yck1509/ConfuserEx). It should fix issues related to C# 6 features.

**Comment by LaraSQP** [comment]
As far as I can tell, it's fixed.

Thank you and good karma to you.
