### ISSUE TITLE
Strange (but positive) output

### ISSUE THREAD

**Issue by MurariAlex** [yck1509/ConfuserEx#447]
Hi, Ki!

After the last commits from 03/05/2016, after confusing a simple exe/dll solution, the output size of the executable assembly is relatively low: 94KB (before 175KB~, I didn't notice any difference in DLLs) and the runtime speed was greatly increased compared to the previous commits.

I do not use compressor.

Until now it's only great news: runtime speed increased, size decreased, everything's working fine.

I browsed the assembly with dnSpy and apparently all protections are there. Maybe I'm wrong because this version is outputing a assembly with half of the size of the previous version.

I use all protections except resources.

What happened?

**Comment by yck1509** [comment]
Hi,
It seems strange, since I did not change much related to protections. Do you have some sample showing the difference between two version of output?

**Comment by MurariAlex** [comment]
Go to the CI Server and download [this version](https://ci.appveyor.com/project/yck1509/confuserex/build/231) and [this version](https://ci.appveyor.com/project/yck1509/confuserex/build/228).

Protect any console app with or without an class library. You'll se the difference.
Use this setting.

```xml
<rule pattern="true" inherit="false">
    <protection id="anti ildasm" />
    <protection id="anti tamper" action="remove">
    </protection>
    <protection id="constants">
      <argument name="mode" value="x86" />
      <argument name="decoderCount" value="10" />
      <argument name="cfg" value="false" />
      <argument name="elements" value="SPI" />
    </protection>
    <protection id="ctrl flow">
      <argument name="predicate" value="expression" />
      <argument name="intensity" value="75" />
      <argument name="depth" value="8" />
      <argument name="junk" value="true" />
    </protection>
    <protection id="anti dump" />
    <protection id="anti debug">
      <argument name="mode" value="antinet" />
    </protection>
    <protection id="invalid metadata" />
    <protection id="ref proxy">
      <argument name="mode" value="strong" />
      <argument name="encoding" value="expression" />
	  <argument name="initCount" value="16" />
      <argument name="depth" value="6" />
      <argument name="internal" value="false" />
      <argument name="typeErasure" value="false" />
    </protection>
    <protection id="resources" action="remove"/>
    <protection id="rename">
      <argument name="renXaml" value="false" />
	  <argument name="renPdb" value="true" />
    </protection>
  </rule>
```

**Comment by yck1509** [comment]
Hi,
It turns out when I modified ObfAttrMarker, I made a mistake that all injected helpers are marked incorrectly so that they don't have any protection applied. 2b4f482 should fix them.
