### ISSUE TITLE
No rules output

### ISSUE THREAD

**Issue by GNormie** [yck1509/ConfuserEx#454]
Greetings

I'm curious about what does ConfuserEX do when i apply no rules since the output is still smaller than the original file size.

I was trying to pinpoint the proper rules to use on a DLL in my application targeted towards Android on Unity and i recently found out a particular feature still presents an erratic behavior even if i run the DLL through ConfuserEX with no rules applied, a straight build runs just fine.

Logcat doesn't seem to be registering any abnormal behavior however the offending method seems to be relying on external calls so i'm totally clueless about what's going on during runtime.

**Comment by yck1509** [comment]
Hi,
Did your method that had error used some special feature? What kind of error did you got?
