### ISSUE TITLE
Declarative obfuscation was broken in the recent build

### ISSUE THREAD

**Issue by wmjordan** [yck1509/ConfuserEx#455]
The attached project could not be obfuscated by the recent build (the released version was fine).

It appeared that the line in the source code was causing the problem.

   [assembly: Obfuscation (Exclude = false, Feature = "namespace 'System.Runtime.CompilerServices':-rename")]

[demo.7z.zip](https://github.com/yck1509/ConfuserEx/files/167140/demo.7z.zip)

**Comment by yck1509** [comment]
Hi,
Since the latest commits, the old syntax was removed and replaced by `namespace('NS'):-rename`.
