### ISSUE TITLE
Excluding namespaces from the ObfuscationAttribute gives a parser error

### ISSUE THREAD

**Issue by LennardF1989** [yck1509/ConfuserEx#510]
I tried to excude 3 namespaces from renaming their class-names using the following:

```
[assembly: Obfuscation(Exclude = false, Feature = "namespace 'myassembly.something.mynamespace':-rename")]
```

But upon obfuscating, it would complain it found an unexpected token: `myassembly.something.mynamespace`

I based the Feature on this issue: https://github.com/yck1509/ConfuserEx/issues/203

The last comment in that issue also mentions the exception about the token I mentioned.

**Comment by joeatsalot** [comment]
It seems to work if I change 
`namespace 'myassembly.something.mynamespace':`
to
`namespace('myassembly.something.mynamespace'):`
... ie. adding brackets around the namespace string.

**Comment by LennardF1989** [comment]
Going to try that out, saves me a lot of work!

**Comment by joeatsalot** [comment]
Hey @yck1509, 
I think the wiki is wrong, and is leading people to problems.
ie. this page:
https://github.com/yck1509/ConfuserEx/wiki/Declarative-Obfuscation

I think the incorrect syntax is the actual problem behind this issue, as well as #203, and maybe more.

**Comment by yck1509** [comment]
Indeed, I changed that syntax in the latest version. I've updated the wiki to reflect this change.
