### ISSUE TITLE
Unable to confuse a library dll

### ISSUE THREAD

**Issue by zipswich** [yck1509/ConfuserEx#522]
Sorry, but  I am not sure whether their is an issue or my lack of understanding.   This seems to be the only place that I ask about it here.
I am trying to confuse a PCL dll, but I am getting the following:

```
...
 [INFO] Finalizing...
 [INFO] Packing...
[ERROR] No executable module!
Failed at 12:23 PM, 0:00 elapsed.
```
Is this an issue or by design.

**Comment by zipswich** [comment]
Packer should not be checked.

**Comment by shytikov** [comment]
Yes, it works if you don't want your file to be packed, but if i WANT that, how to solve?
