### ISSUE TITLE
Add renaming exclusion for private fields with [System.Serializable] attribute

### ISSUE THREAD

**Issue by augiem** [yck1509/ConfuserEx#58]
This isn't an issue as much as a request/idea for a feature. Would it be difficult to add the ability to exclude private fields marked with the [System.Serializable] attribute? There are cases where the names of these variables are important to preserve.

**Comment by fjch1997** [comment]
But why isn't the class names excluded from obfuscation? This way it can support the compatibility of serialized data between obfuscated and unobfuscated version
