### ISSUE TITLE
Unable to rename public members

### ISSUE THREAD

**Issue by VogtVan** [yck1509/ConfuserEx#602]
Hi,

I am evaluating ConfuserEx and I am unable to make rename work. I tried with some dll and the GUI 1.0.0. I tried also with 0.6.0.

The .crproj is simple :

`<project outputDir="C:\confused" baseDir="C:\" xmlns="http://confuser.codeplex.com">
  <module path="some.dll">
    <rule pattern="true" inherit="false">
      <protection id="rename" />
      <protection id="ctrl flow" />
    </rule>
  </module>
</project>`

When I run the confuser, the dll is produced in the output dir, and with ILSpy, Ican see that control flow is obfuscated but none of the namespace names, methods or parameter names are changed.

Of course I have not any ObfuscationAttribute in the code.

What's wrong with my setting ? thank you.

**Comment by bprg** [comment]
[Try latest version.](https://github.com/yck1509/ConfuserEx/releases/download/v1.0.0/ConfuserEx_bin.zip)

**Comment by VogtVan** [comment]
Thank you for the link. But the result is the same !

**Comment by VogtVan** [comment]
After digging a little bit, it appears that it's because I expected ConfuserEx to obfuscate also public members by default, and it seems it doesn't. 

So the question is : is it possible to obfuscate public members, by a mean or another ? 

Thank you.

**Comment by VogtVan** [comment]
Ok. A thing like that seems to work : 

`<protection id="rename">
        <argument name="mode" value="letters" />
	<argument name="renPublic" value="true" />
      </protection>`
