### ISSUE TITLE
Rename 'koi'

### ISSUE THREAD

**Issue by Symbai** [yck1509/ConfuserEx#610]
Is there a way to rename the 'koi' module? I've replaced all koi strings in the project but when opening with ILSpy or similar it still shows koi.

**Comment by SlowLogicBoy** [comment]
you need to modify Confuser source code:
https://github.com/yck1509/ConfuserEx/search?utf8=%E2%9C%93&q=%22koi%22&type=

**Comment by Symbai** [comment]
Already did, however I've forgot one line, now its working thanks.
