### ISSUE TITLE
Obfuscated assemblies run extremely slowly with Windows Defender real-time protection enabled

### ISSUE THREAD

**Issue by danielmda** [yck1509/ConfuserEx#624]
Hello
I noticed one of my applications obfuscated with ConfuserEx started running extremely slowly after a recent Windows update on Windows 10. The culprit process is Windows Defender, and disabling real-time protection fixes the issue. I don't wish to instruct my customers to add my app to Windows Defender's exclusion list.

The app before obfuscation works completely fine with real-time protection enabled. If I run the assembly through ConfuserEx with all settings disabled, the problem remains. So I suspect it's to do with how the obfuscated assembly is created/saved, rather than a specific obfuscation feature. 

Does anyone have any ideas?
Thanks

**Comment by Antonyo** [comment]
In my case I can just recreate only by setting the "Constants protection" on.

![image](https://user-images.githubusercontent.com/3243435/29858969-eadd3a78-8d9a-11e7-9b17-7fc25ccfd7f0.png)

**Comment by Antonyo** [comment]
We've solved by just removing the ConfuserEx metadata watermark and obfuscating the assembly again. Just remove the lines following here: https://github.com/yck1509/ConfuserEx/blob/master/Confuser.Core/ConfuserEngine.cs#L303

Seems that Windows Defender should have marked all assemblies with that metadata as a threat.

**Comment by danielmda** [comment]
Thanks Antonyo, that fixed it! I really appreciate it.

**Comment by FarhadKhalafi** [comment]
Hello,

I have a question about these issues with ConfuserEx: are these fixes
applied to the source code (or any fork of the main branch), or are they
left to the individual users to apply and build from source?

In this specific case, was your fix to delete lines 303 to 327 from
ConfiserEngine.cs?

Thanks

**Comment by Antonyo** [comment]
@FarhadKhalafi I would say it's up to the user to fork the main branch and apply the fixes on their own. 
I'm not in a position to advice the creators about removing their own watermark.
