### ISSUE TITLE
Microsoft Visual Studio 2015 Has stopped

### ISSUE THREAD

**Issue by sherwin14** [yck1509/ConfuserEx#631]
I have successfully obfuscated the dll. But when I used it to integrate with my application.  The Visual Studio 2015 has stopped.

This is the tutorial I followed. 
https://marketplace.visualstudio.com/items?itemName=AvinabMalla.ConfuserExforVisualStudio2015

![image](https://user-images.githubusercontent.com/6423143/31373498-de4ad2a0-adcc-11e7-9e0e-3ef100c8a406.png)

**Comment by Timocop** [comment]
Never use obfuscated binaries while developing. Only obfuscate on releases.

**Comment by anbent** [comment]
I encountered this a few months back and I couldn't find a suitable solution so I ended up developing against non-obfuscated versions of my libraries, and then obfuscating the release versions and shipping my products with those.  However, I want to sell/license some of my libraries which others will need to develop against.  But they will not be able to develop against the obfuscated versions, or so it seems.

So far I have found no way of using an obfuscated assembly to develop against.  I have tried various levels of obfuscation but they all seem to crash VS or throw exceptions preventing you developing your product.

Does anybody know of a sweet spot to obfuscate a DLL to prevent decompilation whilst allowing people to develop against it?

Distributing a non-obfuscated DLL (for development) with an obfuscated one (for release) is not really a viable option as any customer will be easily able to decompile your DLL and get the source, which they can do as they wish with.  So I cannot allow that.

Does anyone have any suggestions?

**Comment by anbent** [comment]
For anyone else who reads this, I have done some more deeper testing and discovered you can select the maximum level but you need to "remove" "anti-debug".  That way the DLL will be successfully loaded by VS and the app but it is prevented from being decompiled (easily).
If you open up the DLL in a decompiler or reflector then you will be able to see the namespaces, class, and public class members but you cannot see/decompile any of the function bodies.
