### ISSUE TITLE
Constant obfuscation causes System.ArgumentException during runtime

### ISSUE THREAD

**Issue by thomK77** [yck1509/ConfuserEx#642]
Hello,

I obfuscate constants with this option:
_[assembly: Obfuscation(Exclude = false, ApplyToMembers = true, Feature = "constants(mode=normal, elements=SI)")]_

I use ConfuserEx version 0.6.0.

Since I use **MSBuild Tools 2015 SP3** to build the project I get the following error during runtime:
_System.ArgumentException: Object must be an array of primitives.
Parameter name: dest
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at ( 23tnIU)[-]_

When I build with an **older version** of the Build Tools the **error does not occur**. When I build with MSBuild Tools 2015 SP3 **without obfuscation** the **error does not occur**.

Any suggestions or hints?
Thanks
Thomas

**Comment by ennerperez** [comment]
Hi, same problem with ConfuserEx version 1.0.0

# Runtime file7.exe
```
Exception: System.ArgumentException: The object must be an array of primitives.
Name of the parameter: dest
   en System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   en ‏⁫‎‍​‫‮‫⁯⁭‍‏‍‬⁮​⁬‮‫⁫‫⁭‏‍⁭‪⁫⁬‏‪‮‏⁪​⁫‪‮‎‫⁭‮[-](UInt32 )
   en file3.Class1.Validate(Operation operation)
   en file3.Class2.Validate(Operation operation)
   en file3.Class3.Save()
   en file7.Form1.ButtonOk_Click(Object sender, EventArgs e)
   en System.Windows.Forms.Control.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   en System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.ButtonBase.WndProc(Message& m)
   en System.Windows.Forms.Button.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Common Language Runtime: 4.0.30319.42000
Operating System: Microsoft Windows NT 6.2.9200.0
Process Type: 64-Bit

# Confuser.crproj

```
<project outputDir="..\..\bin\Release" baseDir="..\bin\Release" xmlns="http://confuser.codeplex.com">
  <rule pattern="true" preset="agressive" />
  <module path="file0.dll" />
  <module path="file1.dll" />
  <module path="file2.dll" />
  <module path="file3.dll" />
  <module path="file4.exe" />
  <module path="file5.exe" />
  <module path="file6.exe" />
  <module path="file7.exe" />
</project>
```

Any suggestions or solution?

**Comment by rafael-biz** [comment]
Hi, I had exactly the same problem described by @thomK77 after updating MSBuild.

**Comment by thomK77** [comment]
What finally worked for me is not to obfuscate array initializers any more. Now I use this config:

`[assembly: Obfuscation(Exclude = false, ApplyToMembers = true, Feature = "constants(elements=S)")]`
