### ISSUE TITLE
[ERROR] Unknown error occurred.

### ISSUE THREAD

**Issue by attiaight** [yck1509/ConfuserEx#663]
I am confusing two projects which are referencing Newtonsoft.Json. One of them get confused fine while on other I am facing following error. I used both v 1.0.0 and 1.0.0-2-gc5b3753.

>  [INFO] Initializing...
> [DEBUG] Building pipeline...
>  [INFO] Resolving dependencies...
> [DEBUG] Checking Strong Name...
> [DEBUG] Creating global .cctors...
> [DEBUG] Watermarking...
> [DEBUG] Executing 'Name analysis' phase...
> [DEBUG] Building VTables & identifier list...
> [DEBUG] Analyzing...
> [DEBUG] Newtonsoft.Json found, enabling compatibility.
> [ERROR] Unknown error occurred.
> Exception: Confuser.Core.UnreachableException: Unreachable code reached.
>    at Confuser.Renamer.Analyzers.LdtokenEnumAnalyzer.Analyze(ConfuserContext context, INameService service, ProtectionParameters parameters, IDnlibDef def) in e:\Source\Public\Confuser2\Confuser.Renamer\Analyzers\LdtokenEnumAnalyzer.cs:line 53
>    at Confuser.Renamer.AnalyzePhase.Analyze(NameService service, ConfuserContext context, ProtectionParameters parameters, IDnlibDef def, Boolean runAnalyzer) in e:\Source\Public\Confuser2\Confuser.Renamer\AnalyzePhase.cs:line 132
>    at Confuser.Renamer.AnalyzePhase.Execute(ConfuserContext context, ProtectionParameters parameters) in e:\Source\Public\Confuser2\Confuser.Renamer\AnalyzePhase.cs:line 56
>    at Confuser.Core.ProtectionPipeline.ExecuteStage(PipelineStage stage, Action`1 func, Func`1 targets, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ProtectionPipeline.cs:line 139
>    at Confuser.Core.ConfuserEngine.RunPipeline(ProtectionPipeline pipeline, ConfuserContext context) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 221
>    at Confuser.Core.ConfuserEngine.RunInternal(ConfuserParameters parameters, CancellationToken token) in e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:line 175
> Failed at 10:49 AM, 0:02 elapsed.

**Comment by attiaight** [comment]
![err1](https://user-images.githubusercontent.com/39981510/41024254-2b319398-6988-11e8-9b45-f6f59a5a0e27.png)
![err2](https://user-images.githubusercontent.com/39981510/41024255-2b68a07c-6988-11e8-8518-30059a0eaf09.png)

**Comment by attiaight** [comment]
Found the problem. Issue # 445 suggested that the dll should not depend on any other than System dependencies, so traced one by one and found one old dll which is already obfuscated.

**Comment by waelshamiri** [comment]
Help me plzzzzzzzzz!

[ERROR] Failed to resolve dependency of 'WpfApp1.exe'.
1> Exception: dnlib.DotNet.AssemblyResolveException: Could not resolve assembly: Microsoft.AspNetCore.SignalR.Client.Core, Version=1.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
1> عند dnlib.DotNet.Extensions.ResolveThrow(IAssemblyResolver self, IAssembly assembly, ModuleDef sourceModule) في E:\Source\Public\Confuser2\dnlib\src\DotNet\IAssemblyResolver.cs:السطر 113
1> عند Confuser.Core.ConfuserEngine.Inspection(ConfuserContext context) في e:\Source\Public\Confuser2\Confuser.Core\ConfuserEngine.cs:السطر 264
1> Failed at 06:30 م, 0:00 elapsed.

I need a help and I thank everyone who can help me
