### ISSUE TITLE
DLL does not work after obfuscation

### ISSUE THREAD

**Issue by ritesh9** [yck1509/ConfuserEx#68]
I am using confuser for first time. ConfuserEx - Exe v0.2.3

(1) Exe, 64 bit, Framework 4.5

warnings occur everytime:
could not found resource type ''.
could not found resource type assembly.resources

with packer:
Maximum - Exe does not run.
Aggressive - exe does not run
Normal - exe does not run
Minimum - exe runs.

Without packer:
Maximum - exe does not run.
Normal - exe runs.

(2) VB.Net DLL, 32 bit, Visual Studio 2013 (Update 2)
Framework 4.5

Warning occurs everytime:
could not found resource type assembly.resources

Maximum - While adding the dll, Visual Studio stops working
Aggressive - While adding the dll, Visual Studio stops working
Normal - While adding the dll, Visual Studio stops working

Minimum -

Visual Studio does not stop working.

It changes the parameters name of public functions.
Executing the function from dll, following error occurs:

An unhandled exception of type 'System.IO.FileNotFoundException' occurred in System.Windows.Forms.dll

Additional information: Could not load file or assembly 'AssemblyName, Version=version, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

Tell me if I am doing wrong or what to do so that I can use DLL file after obfuscating with maximum protection. I also want to protect Exe maximum.

**Comment by syyang1982** [comment]
Hello yck1509, 

It seems the same issue happens at my side as well.  Below is the output log.  

The .NET dll is 32-bit,  Framework 4.5 and  build with VS2013 update 5

 [INFO] ConfuserEx v0.5.0 Copyright (C) Ki 2014
 [INFO] Running on Microsoft Windows NT 6.1.7601 Service Pack 1, .NET Framework v4.0.30319.18408, 64 bits
[DEBUG] Discovering plugins...
 [INFO] Discovered 10 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
 [INFO] Loading 'TestProgram_VC7824.dll'...
 [INFO] Initializing...
[DEBUG] Building pipeline...
 [INFO] Resolving dependencies...
[DEBUG] Checking Strong Name...
[DEBUG] Creating global .cctors...
[DEBUG] Watermarking...
[DEBUG] Executing 'Name analysis' phase...
[DEBUG] Building VTables & identifier list...
[DEBUG] Analyzing...
 [WARN] Could not find resource type 'TP_VC7824.Resources'.
 [INFO] Processing module 'TestProgram_VC7824.dll'...
[DEBUG] Executing 'Invalid metadata addition' phase...
[DEBUG] Executing 'Renaming' phase...
[DEBUG] Renaming...
[DEBUG] Executing 'Anti-debug injection' phase...
[DEBUG] Executing 'Anti-dump injection' phase...
[DEBUG] Executing 'Anti-ILDasm marking' phase...
[DEBUG] Executing 'Encoding reference proxies' phase...
[DEBUG] Executing 'Constant encryption helpers injection' phase...
[DEBUG] Executing 'Resource encryption helpers injection' phase...
[DEBUG] Executing 'Constants encoding' phase...
[DEBUG] Executing 'Anti-tamper helpers injection' phase...
[DEBUG] Executing 'Control flow mangling' phase...
[DEBUG] Executing 'Post-renaming' phase...
[DEBUG] Executing 'Anti-tamper metadata preparation' phase...
[DEBUG] Executing 'Packer info extraction' phase...
 [INFO] Writing module 'TestProgram_VC7824.dll'...
[DEBUG] Encrypting resources...
 [INFO] Finalizing...
[DEBUG] Saving to 'E:\Temp\Confused Assembly\TestProgram_VC7824.dll'...
[DEBUG] Executing 'Export symbol map' phase...
 [INFO] Done.
