### ISSUE TITLE
Problem with ILMerge / Newtonsoft.Json

### ISSUE THREAD

**Issue by novikk** [yck1509/ConfuserEx#79]
Hello,
my app uses Newtonsoft.Json.dll, and I want to only distribute a exe file so I used ILMerge to merge the exe with the dll.
The thing is that if I then use ConfuserEx, it breaks Newtonsoft.Json and the app doesn't work.
So I tried to use first ConfuserEx to confuse only the exe, and then use ILMerge to merge the confused exe + dll, but then ILMerge doesn't recognize the confused exe as a .NET assembly.

How can I fix this?

**Comment by bishtawi** [comment]
How do I exclude certain classes from being renamed? I am trying to serialize some objects to json using Newtonsoft.Json and ConfuserEx is messing it up.
