### ISSUE TITLE
After obfuscation none of my applications will run

### ISSUE THREAD

**Issue by simonhamelech** [yck1509/ConfuserEx#84]
I have 3 console applications and an mvc 5 website dll that after ofuscation with confuserex at any level other than None causes the application to immediately crash.
I tried running confuserex both from the command line and the GUI (see output below) version 0.2.3 but with the same outcome.
My .Net 4.5 C# code is built using VS2013 (update 2) on Windows 7.
The only thing that I may be doing differently is that the target is Release and x64.

Thanks in advance,

Simon
# crproj

```
<project outputDir="C:\Dev\pangea\PangeaImporter\bin\x64\Release\Obfuscated" baseDir="C:\Dev\pangea\PangeaImporter\bin\x64\Release" xmlns="http://confuser.codeplex.com">
  <rule pattern="true" preset="minimum" inherit="false" />
  <module path="PangeaImporter.exe">
    <rule pattern="true" preset="minimum" />
  </module>
  <module path="PangeaAdmin.dll">
    <rule pattern="true" preset="minimum" />
  </module>
</project>
```
# Output

[INFO] ConfuserEx v0.2.0-custom Copyright (C) Ki 2014
 [INFO] Running on Microsoft Windows NT 6.1.7601 Service Pack 1, .NET Framework v4.0.30319.18444, 64 bits
[DEBUG] Discovering plugins...
 [INFO] Discovered 10 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
 [INFO] Loading 'PangeaImporter.exe'...
 [INFO] Loading 'PangeaAdmin.dll'...
 [INFO] Initializing...
[DEBUG] Building pipeline...
 [INFO] Resolving dependencies...
[DEBUG] Checking Strong Name...
[DEBUG] Creating global .cctors...
[DEBUG] Watermarking...
[DEBUG] Executing 'Name analysis' phase...
[DEBUG] Building VTables & identifier list...
[DEBUG] Analyzing...
 [INFO] Processing module 'PangeaImporter.exe'...
[DEBUG] Executing 'Invalid metadata addition' phase...
[DEBUG] Executing 'Renaming' phase...
[DEBUG] Renaming...
[DEBUG] Executing 'Anti-debug injection' phase...
[DEBUG] Executing 'Anti-dump injection' phase...
[DEBUG] Executing 'Anti-ILDasm marking' phase...
[DEBUG] Executing 'Encoding reference proxies' phase...
[DEBUG] Executing 'Constant encryption helpers injection' phase...
[DEBUG] Executing 'Resource encryption helpers injection' phase...
[DEBUG] Executing 'Constants encoding' phase...
[DEBUG] Executing 'Anti-tamper helpers injection' phase...
[DEBUG] Executing 'Control flow mangling' phase...
[DEBUG] Executing 'Post-renaming' phase...
[DEBUG] Executing 'Anti-tamper metadata preparation' phase...
 [INFO] Processing module 'PangeaAdmin.dll'...
[DEBUG] Executing 'Invalid metadata addition' phase...
[DEBUG] Executing 'Renaming' phase...
[DEBUG] Renaming...
[DEBUG] Executing 'Anti-debug injection' phase...
[DEBUG] Executing 'Anti-dump injection' phase...
[DEBUG] Executing 'Anti-ILDasm marking' phase...
[DEBUG] Executing 'Encoding reference proxies' phase...
[DEBUG] Executing 'Constant encryption helpers injection' phase...
[DEBUG] Executing 'Resource encryption helpers injection' phase...
[DEBUG] Executing 'Constants encoding' phase...
[DEBUG] Executing 'Anti-tamper helpers injection' phase...
[DEBUG] Executing 'Control flow mangling' phase...
[DEBUG] Executing 'Post-renaming' phase...
[DEBUG] Executing 'Anti-tamper metadata preparation' phase...
[DEBUG] Executing 'Packer info extraction' phase...
 [INFO] Writing module 'PangeaImporter.exe'...
[DEBUG] Executing 'Packer info extraction' phase...
 [INFO] Writing module 'PangeaAdmin.dll'...
 [INFO] Finalizing...
[DEBUG] Saving to 'C:\Dev\pangea\PangeaImporter\bin\x64\Release\Obfuscated\PangeaImporter.exe'...
[DEBUG] Saving to 'C:\Dev\pangea\PangeaImporter\bin\x64\Release\Obfuscated\PangeaAdmin.dll'...
 [INFO] Done.
Finished at 4:00 AM, 0:00 elapsed.

**Comment by zaryk** [comment]
I know this is old post, but I am using MVC 4.  It kept crashing when I had anti-dump,  I believe it works with constants and rename as well, but wanted to be safe.  Can't say if it is the same issue reported, here is my config.  I think it is dependent on what your code is doing though.

```
<project outputDir="Confused" baseDir=".\bin" debug="true" xmlns="http://confuser.codeplex.com">
  <rule pattern="true" preset="normal" inherit="false">
    <protection id="anti ildasm" action="remove" />
    <protection id="anti tamper" />
    <protection id="constants"  action="remove" />
    <protection id="ctrl flow" />
    <protection id="anti dump"  action="remove" />
    <protection id="anti debug" />
    <protection id="invalid metadata" />
    <protection id="ref proxy" />
    <protection id="resources" />
    <protection id="rename"  action="remove" />
  </rule>
  <module path="IdeaBox.dll" />
  <module path="Zarysoft.dll" />
</project>
```
