### ISSUE TITLE
Application does not start after protection.

### ISSUE THREAD

**Issue by vSun** [yck1509/ConfuserEx#96]
Application does not work after protection. 

I am using Fody (https://github.com/Fody/Costura) to embed all dll files (ZeroMQ and Newton.Json)
# Result of ConfuserEX v0.2.3 

 [INFO] ConfuserEx v0.2.3 Copyright (C) Ki 2014
 [INFO] Running on Microsoft Windows NT 6.1.7601 Service Pack 1, .NET Framework v4.0.30319.18444, 64 bits
[DEBUG] Discovering plugins...
 [INFO] Discovered 10 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
 [INFO] Loading 'TYS.exe'...
 [INFO] Initializing...
[DEBUG] Building pipeline...
 [INFO] Resolving dependencies...
[DEBUG] Checking Strong Name...
[DEBUG] Creating global .cctors...
[DEBUG] Watermarking...
[DEBUG] Executing 'Name analysis' phase...
[DEBUG] Building VTables & identifier list...
[DEBUG] Analyzing...
 [INFO] Processing module 'TYS.exe'...
[DEBUG] Executing 'Invalid metadata addition' phase...
[DEBUG] Executing 'Renaming' phase...
[DEBUG] Renaming...
[DEBUG] Executing 'Anti-debug injection' phase...
[DEBUG] Executing 'Anti-dump injection' phase...
[DEBUG] Executing 'Anti-ILDasm marking' phase...
[DEBUG] Executing 'Encoding reference proxies' phase...
[DEBUG] Executing 'Constant encryption helpers injection' phase...
[DEBUG] Executing 'Resource encryption helpers injection' phase...
[DEBUG] Executing 'Constants encoding' phase...
[DEBUG] Executing 'Anti-tamper helpers injection' phase...
[DEBUG] Executing 'Control flow mangling' phase...
[DEBUG] Executing 'Post-renaming' phase...
[DEBUG] Executing 'Anti-tamper metadata preparation' phase...
[DEBUG] Executing 'Packer info extraction' phase...
 [INFO] Writing module 'koi'...
 [INFO] Finalizing...
 [INFO] Packing...
[DEBUG] Encrypting modules...
 [INFO] Protecting packer stub...
[DEBUG] Discovering plugins...
 [INFO] Discovered 11 protections, 1 packers.
[DEBUG] Resolving component dependency...
 [INFO] Loading input modules...
 [INFO] Loading 'TYS.exe'...
 [INFO] Initializing...
[DEBUG] Building pipeline...
 [INFO] Resolving dependencies...
[DEBUG] Checking Strong Name...
[DEBUG] Creating global .cctors...
[DEBUG] Watermarking...
[DEBUG] Executing 'Name analysis' phase...
[DEBUG] Building VTables & identifier list...
[DEBUG] Analyzing...
 [WARN] Could not found resource type 'Com.VA.TYS.FormMain'.
 [WARN] Could not found resource type 'TYS.Properties.de'.
 [WARN] Could not found resource type 'TYS.Properties.tr'.
 [WARN] Could not found resource type 'Com.VA.TYS.FormActivate'.
 [WARN] Could not found resource type 'TYS.Properties.en'.
 [INFO] Processing module 'TYS.exe'...
[DEBUG] Executing 'Packer info encoding' phase...
[DEBUG] Executing 'Invalid metadata addition' phase...
[DEBUG] Executing 'Renaming' phase...
[DEBUG] Renaming...
[DEBUG] Executing 'Anti-debug injection' phase...
[DEBUG] Executing 'Anti-dump injection' phase...
[DEBUG] Executing 'Anti-ILDasm marking' phase...
[DEBUG] Executing 'Encoding reference proxies' phase...
[DEBUG] Executing 'Constant encryption helpers injection' phase...
[DEBUG] Executing 'Resource encryption helpers injection' phase...
[DEBUG] Executing 'Constants encoding' phase...
[DEBUG] Executing 'Anti-tamper helpers injection' phase...
[DEBUG] Executing 'Control flow mangling' phase...
[DEBUG] Executing 'Post-renaming' phase...
[DEBUG] Executing 'Anti-tamper metadata preparation' phase...
[DEBUG] Executing 'Packer info extraction' phase...
 [INFO] Writing module 'TYS.exe'...
 [INFO] Finalizing...
[DEBUG] Saving to 'C:\Users\DS\AppData\Local\Temp\ekg5f3vj.qyc\yoztlumv.ssi\TYS.exe'...
 [INFO] Finish protecting packer stub.
[DEBUG] Saving to 'C:\Users\DS\Desktop\TYS\bin\Release\Confused\TYS.exe'...
 [INFO] Done.
Finished at 18:24, 0:00 elapsed.

**Comment by pkunze** [comment]
I am experiencing a similar issue. I'd like to use confuser ex v0.4.0 but when i try to use the packer, i get similar warnings and the output does not work as well. 

The log is quite long, so i will post only the part i gues should be relevant. It is quite similar to the one above... 

    [INFO] Finalizing...
     [INFO] Packing...
    [DEBUG] Encrypting modules...
     [INFO] Protecting packer stub...
    [DEBUG] Discovering plugins...
     [INFO] Discovered 11 protections, 1 packers.
    [DEBUG] Resolving component dependency...
     [INFO] Loading input modules...
     [INFO] Loading 'My.exe'...
     [INFO] Initializing...
    [DEBUG] Building pipeline...
    [DEBUG] Executing 'Module injection' phase...
     [INFO] Resolving dependencies...
    [DEBUG] Checking Strong Name...
    [DEBUG] Creating global .cctors...
    [DEBUG] Watermarking...
    [DEBUG] Executing 'Name analysis' phase...
    [DEBUG] Building VTables & identifier list...
    [DEBUG] Analyzing...
     [WARN] Could not found resource type '⁮‎‭‪‫‫⁭⁬⁪‬⁪‫⁪‪‏‬⁫‏⁬⁭⁪⁮‮⁭⁯‌​‭‍⁮‭⁬‏‬⁪‬‫⁮​‮'.
     [WARN] Could not found resource type '⁮‏‬‎⁮⁯‭‏‍⁭‬‍⁫⁭‏‮⁯‬⁫⁪⁮⁬⁬⁬⁯‫⁪⁭‭⁭⁬‭⁮‏⁮‍⁯⁭‪‮'.
     [WARN] Could not found resource type '‎‌‬⁯​⁬‮⁪‍⁯‪‌‍‌‭‭‌⁬‏‪‫‭⁯⁮‎⁯⁫‫​​‌⁮⁮‭‫⁪‫‍‫‮'.
     [WARN] Could not found resource type '‏‪‮⁫‮‪​⁬⁬⁫⁬‬‪‭⁬‌⁮‍‬⁯‭⁮‭‌⁬⁪‌‏‭⁪​⁪⁯‮‏‌⁬⁮⁭‮'.
     [WARN] Could not found resource type '‫‏⁯⁯⁮⁪‍‎‍​⁮⁫‏​⁫‬‏‫⁪‫⁪‎⁯‍⁮‪​⁪‫⁬‏⁫⁯⁪⁮‍⁫‍⁯‮'.
     [WARN] Could not found resource type '​⁪‪‭‏‬‏⁭‭‏‎‮⁫⁪⁯⁪‏⁫⁭‪⁭⁮​‭‬⁬⁬‪​⁭‏⁪‪‪​⁫‪⁬​‮'.
     [WARN] Could not found resource type '‬‍⁭‎‬⁯⁬‭⁪‬‌⁪‬⁬⁭‭‭‎​​‌‪‪‏‬⁪​‎‎‪⁭‍‭⁮‎⁬‮⁪‫‮'.
     [WARN] Could not found resource type '⁮‍‎‬⁫‏⁯​⁬⁯⁮⁫‮‪⁬‬‫‪⁮⁬⁯​‌⁯‪‌‌⁪‎⁮‍⁪‍⁪‌⁮⁬⁫‍‮'.
     [INFO] Processing module 'My.exe'...
    [DEBUG] Executing 'Packer info encoding' phase...
    [DEBUG] Executing 'Invalid metadata addition' phase...
    [DEBUG] Executing 'Renaming' phase...
    [DEBUG] Renaming...
    [DEBUG] Executing 'Anti-debug injection' phase...
    [DEBUG] Executing 'Anti-dump injection' phase...
    [DEBUG] Executing 'Anti-ILDasm marking' phase...
    [DEBUG] Executing 'Encoding reference proxies' phase...
    [DEBUG] Executing 'Constant encryption helpers injection' phase...
    [DEBUG] Executing 'Resource encryption helpers injection' phase...
    [DEBUG] Executing 'Constants encoding' phase...
    [DEBUG] Executing 'Anti-tamper helpers injection' phase...
    [DEBUG] Executing 'Control flow mangling' phase...
    [DEBUG] Executing 'Post-renaming' phase...
    [DEBUG] Executing 'Anti-tamper metadata preparation' phase...
    [DEBUG] Executing 'Packer info extraction' phase...
     [INFO] Writing module 'My.exe'...
     [INFO] Finalizing...
    [DEBUG] Saving to 'C:\Users\Me\AppData\Local\Temp\oxjtv33a.pn2\zokdtnx1.t4c\My.exe'...
    [DEBUG] Executing 'Export symbol map' phase...
     [INFO] Finish protecting packer stub.
    [DEBUG] Saving to 'D:\Path\To\My.exe'...
    [DEBUG] Executing 'Export symbol map' phase...
     [INFO] Done.
    Finished at 10:45, 0:22 elapsed.

**Comment by yck1509** [comment]
Is your input file already obfuscated? Modification to obfuscated files might break them.

**Comment by pkunze** [comment]
Thanks for your reply! I will check this.

**Comment by pkunze** [comment]
No, unfortunately, this doe not seem to be the problem. I obfuscated right after the build.

**Comment by yck1509** [comment]
You might want to try the latest version (v0.5). Also, if you don't mind, you could send the files to confuser.net@gmail.com and I'll try to see what's wrong with it.

**Comment by pkunze** [comment]
Hi, i just tried it out. Unfortunately, v0.5 does not solve the Issue. I can not send you the files either, since this is for work and therefore, i am not permitted to do so. However, maybe i can give you some further information which might be helpful:

1. There is an packed `.exe` in the output directory which does not work by itsself (as you already know)
2. If i put the dependecies (`*.dll`) into the outputdirectory, executing the ´.exe´-file works fine

I hope this is not to obvious. Maybe I can reproduce the case someday in my freetime. In this case, I will gladly send you the files to reproduce the issue.

Anyway, thanks a lot for you Work and for taking the time to respond so quickly! Seriously.
