### ISSUE TITLE
Confuser CLI prompts "Press any key...." when running in our build server

### ISSUE THREAD

**Issue by sushiat** [yck1509/ConfuserEx#97]
Hi,

We are using Bamboo to build and deploy our applications and I added ConfuserEx as a deployment step. When running the current test deployment I can see the following exception being thrown:

Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
01-Oct-2014 11:27:52       at System.Console.ReadKey(Boolean intercept)
01-Oct-2014 11:27:52       at Confuser.CLI.Program.Main(String[] args) in e:\Source\Public\Confuser2\Confuser.CLI\Program.cs:line 49

Could we add a project property or command line parameter to override the logic in the NeedPause() method?

Thx,
Markus

**Comment by Gaushick** [comment]
Any documentation for ConfuserEx using CLI?
